const independentReviewedHashes = {
  'independent.application.braun': '8813ce6d40ad2f27',
  'independent.application.guay': '40ee48f62b153d32',
  'independent.application.jarocinski': 'ccf9a4ead83418ce',
  'independent.application.lms': 'efd17d1e84fd8b74',
  'independent.combination.drautzburg-wright': '6fb1f5626d42a138',
  'independent.combination.keweloh-wang': '00ede9be4e94de3f',
  'independent.estimation.guay': '06b4fbad7cac05de',
  'independent.estimation.hafner': 'ca438270396ab4b6',
  'independent.estimation.keweloh': '2c985ff39da19c9a',
  'independent.estimation.lewis': '17496b50839366c0',
  'independent.limits.common-volatility': '95f1080e1e66c0c9',
  'independent.limits.mesters-zwiernik': 'd476ec99a67c3b4e',
  'independent.limits.nonlinearity': 'c40c9f0f1aee567c',
  'independent.limits.weak-and-labels': '040d2757f40a5399',
  'independent.origins.bonhomme-robin': '55bbd61bb72527c4',
  'independent.origins.chen-bickel': 'aeef3d90d583bee5',
  'independent.origins.comon': '296e61a9ba418d41',
  'independent.origins.gmr': 'e9e242fd7ee011e7',
  'independent.origins.lms': 'a69b9d41ce322fa0',
};
const pageReviewedHashes = {
  'overview.origins.sims-critique': '983e2c3c35d39721',
  'overview.origins.sims-orthogonalization': '1af01b234ea39594',
  'overview.rotations.rrwz': '2f3650f63f3d2311',
  'recursive.origins.sims': '857cb5dcce5d3ad8',
  'recursive.origins.kilian-lutkepohl': '33d608be50fdc46f',
  'recursive.applications.cee': '9ef43755102c91bc',
  'recursive.applications.kilian': '973d895d3eaa5433',
  'recursive.applications.blanchard-perotti': 'bedccbecc41aea37',
  'recursive.extensions.keweloh-wang': 'c8d68acb758a1c39',
  'recursive.limits.pesaran-shin': '6c0b235552e05934',
  'sign.origins.faust': '44c389095ff8ad2f',
  'sign.origins.canova-de-nicolo': '0b2abb2e0eeb2fd1',
  'sign.origins.uhlig': '9f36f1effb197529',
  'sign.applications.mountford-uhlig': '35fee30fdf002c6b',
  'sign.applications.kilian-murphy': 'ae7acdb1418956cd',
  'sign.extensions.antolin-diaz': 'a4a851e163d52e6b',
  'sign.extensions.braun-brueggemann': 'ea791bff6997b056',
  'sign.inference.rrwz': '3a90caae26e32091',
  'sign.inference.arias': '27ccfa8f6f21b6f3',
  'sign.reporting.kilian-lutkepohl': '99e1a89647a29cfc',
  'narrative.origins.romer-romer-1989': '3e0103d946413ac8',
  'narrative.origins.romer-romer-2010': 'cfaeddf9e9cddf84',
  'narrative.origins.ramey': '9950eb6ed59851da',
  'narrative.origins.kilian': 'dce0ec28af29e7c5',
  'narrative.variants.shock-sign': '9895935558929a1c',
  'narrative.variants.historical-decomposition': 'f54910be3f98414c',
  'narrative.applications.antolin-diaz': '193b4c0ef1dfd0c2',
  'narrative.applications.ludvigson-ma-ng': '885f2a3da618d630',
  'narrative.inference.antolin-diaz': '312a90fc493b73b1',
  'long-run.origins.blanchard-quah': 'af4770db704f4855',
  'long-run.identification.blanchard-quah': '6112638b705620ea',
  'long-run.stationary.kilian-lutkepohl': '94c35a7b841770ea',
  'long-run.cointegration.kilian-lutkepohl': '2977be6c04446a27',
  'long-run.applications.kpsw': '5c3fa4793b73df60',
  'long-run.applications.gali': 'a5c576fcecacf3fe',
  'long-run.applications.beaudry-portier': '6268aac5e6d51696',
  'long-run.limits.kurmann-mertens': '215eca019345a435',
  'long-run.limits.faust-leeper': '1d3c49e33604bd4b',
  'max-share.origins.uhlig': '1790a0b6f2b20fc7',
  'max-share.origins.barsky-sims': 'd72a8f76886b112d',
  'max-share.sequential.caldara': 'ed380bb862190851',
  'max-share.sequential.caldara-reverse': 'dc0f76a9e4587eb0',
  'max-share.joint.carriero-volpicella': '41ae98743bca5373',
  'max-share.joint.dominance': '2ba9a78a97f6b9b6',
  'max-share.joint.nonempty': '6e5140ecb92fafe0',
  'max-share.joint.unique': '6204065377a713f7',
  'max-share.implementation.bayesian': 'b805dcfc5bb5b96d',
  'max-share.implementation.frequentist': '80f876d3fd251a02',
  'max-share.limits.confounding': 'c5b29b9e07a7700d',
  'max-share.limits.simulation': '0ed7521289471dde',
  'heteroskedasticity.origins.sentana': '11ec715677252911',
  'heteroskedasticity.origins.rigobon': '0ce5f3407cf14df9',
  'heteroskedasticity.limits.proportional': '8ade7cd599b4fc52',
  'heteroskedasticity.variants.llm-model': 'a2af0e85d20e06bb',
  'heteroskedasticity.variants.llm-testing': 'd4b49d52a5305300',
  'heteroskedasticity.variants.llm-state-invariance': 'f61465ab49813d9e',
  'heteroskedasticity.variants.milunovich-yang': '18b6c9c4fa0c2acf',
  'heteroskedasticity.variants.lutkepohl-netsunajev': '681a4cd0817c1492',
  'heteroskedasticity.variants.lewis': 'aefbfdc8b34e1a18',
  'heteroskedasticity.variants.lewis-rank': '615b72ad77018381',
  'heteroskedasticity.variants.bertsche-braun': '36b2ef5c4c0c84b0',
  'heteroskedasticity.variants.bertsche-braun-estimation': '8bce72b551075f84',
  'heteroskedasticity.variants.virolainen': 'df9e9571e099fb6e',
  'heteroskedasticity.variants.virolainen-partial': 'b5b91d804d1a3dc3',
  'heteroskedasticity.applications.rigobon-sack': 'd6f4d961a9e82739',
  'heteroskedasticity.applications.normandin-method': 'c989230051244315',
  'heteroskedasticity.applications.normandin-targets': '140ad08e440b549f',
  'heteroskedasticity.applications.normandin-orthogonality': '73884c0de5fcbb23',
  'heteroskedasticity.applications.lewis': '6945efaf5ec697e7',
  'heteroskedasticity.applications.bertsche-braun': 'd2af53ba3e74b334',
  'heteroskedasticity.limits.mopmq-separation': '108fa298617b9ae7',
  'heteroskedasticity.limits.mopmq-weak': '2f33239d0994d23f',
  'heteroskedasticity.limits.kpm-causal': 'cdf296f9de82ba0d',
  'heteroskedasticity.limits.kpm-sets': 'ff29faa012ced38d',
  'proxy.origins.stock-watson': 'd989bce9e23b5437',
  'proxy.origins.mertens-ravn': 'f01d961628511481',
  'proxy.estimator.kilian-lutkepohl': '33460c8fbb02018f',
  'proxy.inference.mosw': '074ecd54f97a34d3',
  'proxy.identification.miranda-agrippino-ricco': '9e7f602d0275ba8e',
  'proxy.identification.angelini': 'd3f9cbf9f0a98b5d',
  'proxy.bootstrap.jentsch-lunsford-2019': 'baf6ed5fe433fb19',
  'proxy.bootstrap.jentsch-lunsford-2022': 'a6fe2e80516d53d6',
  'proxy.bootstrap.bruns-lutkepohl': '1cccaee19670e2a7',
  'proxy.bayesian.arias': '1affaf58cfd3e5b8',
  'proxy.bayesian.giacomini-kitagawa-read': '39b9f91a415a898d',
  'proxy.applications.gertler-karadi': 'e7d5e6e01c90bfdb',
  'proxy.applications.jarocinski-karadi': 'c2cb96964f6227cb',
  'proxy.applications.kanzig-oil': '7a8c034f4c83c9a5',
  'proxy.applications.kanzig-carbon': 'bbff386f8ca9eafd',
  'proxy.extensions.braun-brueggemann': '827bdda5f1c280e5',
  'proxy.multiple.bruns-lutkepohl-mcneil': '722139ad048d817e',
};

const primaryEvidence = (id, locator, evidence, reviewedFrom, reviewedVersion) => ({
  id,
  relation: 'supports',
  locator,
  evidence,
  reviewedFrom,
  reviewedVersion,
  verdict: 'supports',
});

const pageClaim = (page, id, contentPath, text, source, reviewedAt = '2026-07-16') => ({
  id,
  page,
  contentPath,
  text,
  claimType: 'paper-dependent',
  evidenceContract: 'primary-v1',
  sources: [source],
  status: 'verified',
  reviewedAt,
  reviewedHash: pageReviewedHashes[id] ?? '',
});

const independentClaim = (id, contentPath, text, source) => ({
  id,
  page: 'independent-shocks',
  contentPath,
  text,
  claimType: 'paper-dependent',
  evidenceContract: 'primary-v1',
  sources: [source],
  status: 'verified',
  reviewedAt: '2026-07-16',
  reviewedHash: independentReviewedHashes[id] ?? '',
});

export const atlasClaims = {
  'overview.origins.sims-critique': pageClaim(
    'overview',
    'overview.origins.sims-critique',
    '#atlas-literature-origins',
    'Sims (1980, Section 1 and Section 2.C) argued that the usual identifying restrictions in large macroeconomic models were not credible and proposed an unrestricted multivariate time-series strategy.',
    primaryEvidence(
      'sims-1980',
      'Section 1 and Section 2.C, pp. 1&ndash;2 and 14&ndash;18',
      'Sims calls the conventional large-model identifying restrictions incredible and develops a six-variable dynamic system without cross-equation a priori restrictions as the empirical alternative.',
      'raw/sims-1980-macroeconomics-reality/Sims-MacroeconomicsReality-1980.md',
      'Econometrica 48(1), 1980',
    ),
  ),
  'overview.origins.sims-orthogonalization': pageClaim(
    'overview',
    'overview.origins.sims-orthogonalization',
    '#atlas-literature-origins',
    'He also stated that the triangular transformation used to orthogonalize his VAR innovations had no unique best form.',
    primaryEvidence(
      'sims-1980',
      'Section 2.C, pp. 17&ndash;18',
      'When transforming correlated VAR residuals into orthogonal shocks for display, Sims states that there is no unique best transformation and then adopts one triangular ordering.',
      'raw/sims-1980-macroeconomics-reality/Sims-MacroeconomicsReality-1980.md',
      'Econometrica 48(1), 1980',
    ),
  ),
  'overview.rotations.rrwz': pageClaim(
    'overview',
    'overview.rotations.rrwz',
    '#atlas-literature-rotations',
    'Rubio-Ramirez, Waggoner, and Zha (2010, Theorem 1 and Algorithm 1) show that observationally equivalent SVAR parameterizations differ by orthogonal rotations and provide rank conditions and algorithms for exact restrictions.',
    primaryEvidence(
      'rubio-ramirez-waggoner-zha-2010',
      'Section 2.2; Theorem 1; Algorithm 1',
      'Section 2.2 characterizes observational equivalence through a common orthogonal matrix; Theorem 1 supplies the global rank condition and Algorithm 1 constructs the rotation satisfying exact admissible restrictions.',
      'raw/rubio-ramirez-waggoner-zha-2010-svar-identification/77-2-665.md',
      'Review of Economic Studies 77(2), 2010',
    ),
  ),
  'recursive.origins.sims': pageClaim(
    'recursive',
    'recursive.origins.sims',
    'literatureSections.0.body',
    'Sims (1980, Section 2.C) orthogonalized correlated VAR innovations with a triangular ordering but stated that there was no unique best transformation.',
    primaryEvidence(
      'sims-1980',
      'Section 2.C, pp. 17&ndash;18',
      'Sims uses a triangular ordering to orthogonalize correlated residuals and explicitly says that no unique best orthogonalization exists.',
      'raw/sims-1980-macroeconomics-reality/Sims-MacroeconomicsReality-1980.md',
      'Econometrica 48(1), 1980',
    ),
  ),
  'recursive.origins.kilian-lutkepohl': pageClaim(
    'recursive',
    'recursive.origins.kilian-lutkepohl',
    'literatureSections.0.body',
    'Kilian and L&uuml;tkepohl (2017, Chapter 8, Section 8.2) show that a lower-triangular Cholesky factor supplies K(K-1)/2 impact zeros and emphasize that the resulting recursive ordering needs an economic justification.',
    primaryEvidence(
      'kilian-lutkepohl-2017',
      'Chapter 8, Section 8.2',
      'The chapter derives the K(K-1)/2 zero entries of the lower-triangular Cholesky factor and warns that the implied recursive causal chain is meaningful only with a plausible economic interpretation.',
      'raw/kilian-2016-structural-var-analysis-chapter-8-identification-by-short-run-restrictions/SVARch08.md',
      'Cambridge University Press book chapter, 2017 edition',
    ),
  ),
  'recursive.applications.cee': pageClaim(
    'recursive',
    'recursive.applications.cee',
    'literatureSections.1.body',
    'Christiano, Eichenbaum, and Evans (2005, Section II) identify a monetary-policy shock by ordering variables around the federal funds rate so that one block cannot respond within the period and the policy authority observes another block only with a lag.',
    primaryEvidence(
      'christiano-eichenbaum-evans-2005',
      'Section II, pp. 4&ndash;7',
      'The VAR partitions variables around the federal funds rate and states the two timing assumptions: one block does not respond contemporaneously to the policy shock, while the policy authority observes the other block only with a lag.',
      'raw/christiano-eichenbaum-evans-2005-nominal-rigidities/426038.md',
      'Journal of Political Economy 113(1), 2005',
    ),
  ),
  'recursive.applications.kilian': pageClaim(
    'recursive',
    'recursive.applications.kilian',
    'literatureSections.1.body',
    'Kilian (2009, Section II.A) identifies three oil-market shocks with a monthly recursive impact matrix motivated by short-run delays.',
    primaryEvidence(
      'kilian-2009',
      'Section II.A, pp. 1055&ndash;1057',
      'Kilian specifies a monthly lower-triangular impact matrix for oil-supply, aggregate-demand, and oil-specific-demand shocks and motivates its zeros with within-month production and activity delays.',
      'raw/kilian-2009-oil-price-shocks-demand-supply/Kilian 2009 - Not all oil price shocks are alike Disentangling demand and supply shocks in the crude oil market.md',
      'American Economic Review 99(3), 2009',
    ),
  ),
  'recursive.applications.blanchard-perotti': pageClaim(
    'recursive',
    'recursive.applications.blanchard-perotti',
    'literatureSections.1.body',
    'Blanchard and Perotti (2002, Section II.B and Appendix A.2) combine fiscal decision lags with externally constructed tax elasticities in a nonrecursive fiscal SVAR.',
    primaryEvidence(
      'blanchard-perotti-2002',
      'Section II.B and Appendix A.2',
      'The identification procedure uses quarterly decision lags to remove discretionary within-quarter feedback and constructs automatic tax responses from institutional tax-base elasticities before estimating the remaining simultaneous effects.',
      'raw/blanchard-perotti-2002-fiscal-policy-shocks/117-4-1329.md',
      'Quarterly Journal of Economics 117(4), 2002',
    ),
  ),
  'recursive.extensions.keweloh-wang': pageClaim(
    'recursive',
    'recursive.extensions.keweloh-wang',
    'literatureSections.1.body',
    'Keweloh and Wang (2025, Sections 4 and 7) use an adaptive ridge penalty to shrink statistically identified non-Gaussian SVAR estimates toward suspected short-run zeros while making the asymptotic effect of invalid restrictions vanish.',
    primaryEvidence(
      'keweloh-wang-2025',
      'Sections 4 and 7; Propositions 2&ndash;3',
      'The ridge SVAR-CSUE penalizes suspected zero entries with adaptive weights; the asymptotic results show vanishing bias from false restrictions and efficiency gains when restrictions are valid.',
      'raw/keweloh-2025-uncertain-short-run-restrictions/Uncertain Short-Run Restrictions and Statistically.md',
      'Journal of Applied Econometrics version, 2025',
    ),
  ),
  'recursive.limits.pesaran-shin': pageClaim(
    'recursive',
    'recursive.limits.pesaran-shin',
    'literatureSections.3.body',
    'Pesaran and Shin (1998, Abstract and Section 3) define generalized impulse responses that do not require shock orthogonalization and are invariant to the ordering of the VAR variables.',
    primaryEvidence(
      'pesaran-shin-1998',
      'Abstract and Section 3, pp. 17&ndash;23',
      'The paper defines generalized impulse responses without orthogonalizing shocks and establishes that they are invariant to variable ordering, unlike Cholesky-orthogonalized responses.',
      'raw/pesaran-1998-generalized-impulse-response-analysis/1-s2.0-S0165176597002140-main.md',
      'Economics Letters 58(1), 1998',
    ),
  ),
  'sign.origins.faust': pageClaim(
    'sign',
    'sign.origins.faust',
    'literatureSections.0.body',
    'Faust (1998, Abstract) evaluates robustness by searching all identifications for the one most adverse to a VAR conclusion, subject to qualitative impulse-response restrictions.',
    primaryEvidence(
      'faust-1998',
      'Abstract',
      'The abstract describes checking every possible identification for the one worst for the claim, subject to the VAR producing reasonable impulse responses.',
      'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=86751',
      'Author-posted April 1998 paper corresponding to the published article',
    ),
    '2026-07-19',
  ),
  'sign.origins.canova-de-nicolo': pageClaim(
    'sign',
    'sign.origins.canova-de-nicolo',
    'literatureSections.0.body',
    'Canova and De Nicol&oacute; (2002, Abstract and Section 3) assign economic labels to orthogonal innovations using signs of dynamic cross-correlations.',
    primaryEvidence(
      'canova-de-nicolo-2002',
      'Abstract and Section 3, pp. 1131 and 1140&ndash;1143',
      'The paper states that its identification approach uses signs of cross-correlation functions after shocks to assign structural interpretations to orthogonal innovations and develops those model-implied patterns in Section 3.',
      'https://crei.cat/wp-content/uploads/users/pages/modima.pdf',
      'Journal of Monetary Economics 49(6), 2002',
    ),
    '2026-07-19',
  ),
  'sign.origins.uhlig': pageClaim(
    'sign',
    'sign.origins.uhlig',
    'literatureSections.0.body',
    'Uhlig (2005, Abstract and Section 2) identifies contractionary monetary-policy shocks by requiring prices and nonborrowed reserves not to rise and the federal funds rate not to fall for a chosen horizon, while leaving real GDP unrestricted.',
    primaryEvidence(
      'uhlig-2005',
      'Abstract; Section 2, Assumption A.1',
      'Uhlig imposes nonpositive responses of prices and nonborrowed reserves and a nonnegative federal-funds-rate response through horizon K, while explicitly imposing no restriction on real GDP.',
      'raw/uhlig-2005-effects-monetary-policy-output-agnostic-identification/Uhlig 2005 - What are the effects of monetary policy on output Results from an agnostic identification procedure.md',
      'Journal of Monetary Economics 52(2), 2005',
    ),
    '2026-07-19',
  ),
  'sign.applications.mountford-uhlig': pageClaim(
    'sign',
    'sign.applications.mountford-uhlig',
    'literatureSections.1.body',
    'Mountford and Uhlig (2009, Summary and Section 1) identify government-revenue and government-spending shocks with sign restrictions while controlling for business-cycle and monetary-policy shocks and allowing announcement effects.',
    primaryEvidence(
      'mountford-uhlig-2009',
      'Summary and Section 1, pp. 960&ndash;964',
      'The paper identifies revenue and spending shocks with signs and orthogonality to sign-identified business-cycle and monetary-policy shocks, and explicitly permits delayed fiscal-variable responses to capture announcements.',
      'raw/mountford-uhlig-2009-effects-fiscal-policy-shocks/J of Applied Econometrics - 2009 - Mountford - What are the effects of fiscal policy shocks.md',
      'Journal of Applied Econometrics 24(6), 2009',
    ),
    '2026-07-19',
  ),
  'sign.applications.kilian-murphy': pageClaim(
    'sign',
    'sign.applications.kilian-murphy',
    'literatureSections.1.body',
    'Kilian and Murphy (2012, Abstract and Sections 3.3&ndash;3.5) show that impact signs alone leave mutually contradictory oil-market models and narrow the set with bounds on the short-run oil-supply elasticity and the impact response of real activity.',
    primaryEvidence(
      'kilian-murphy-2012',
      'Abstract; Sections 3.3&ndash;3.5, pp. 1177&ndash;1182',
      'The unrestricted sign set contains models with opposite oil-price decompositions; an impact supply-elasticity cap reduces the set and a near-zero real-activity impact bound leaves 17 nearly equivalent models.',
      'raw/kilian-2012-agnostic-sign-restrictions-oil-market-var/Kilian Murphy 2012.md',
      'Journal of the European Economic Association 10(5), 2012',
    ),
    '2026-07-19',
  ),
  'sign.extensions.antolin-diaz': pageClaim(
    'sign',
    'sign.extensions.antolin-diaz',
    'literatureSections.1.body',
    'Antol&iacute;n-D&iacute;az and Rubio-Ram&iacute;rez (2018, Abstract and Section II) introduce narrative sign restrictions on recovered shocks and historical-decomposition contributions around dated events.',
    primaryEvidence(
      'antolin-diaz-rubio-ramirez-2018',
      'Abstract and Section II, pp. 2802&ndash;2810',
      'The paper defines narrative restrictions that make candidate structural shocks or historical decompositions agree with sign or importance statements about selected historical episodes.',
      'raw/antolindiaz-2018-narrative-sign-restrictions/AntolnDaz-NarrativeSignRestrictions-2018.md',
      'American Economic Review 108(10), 2018',
    ),
    '2026-07-19',
  ),
  'sign.extensions.braun-brueggemann': pageClaim(
    'sign',
    'sign.extensions.braun-brueggemann',
    'literatureSections.1.body',
    'Braun and Br&uuml;ggemann (2023, Abstract and Sections 2.2&ndash;2.3) combine sign restrictions with valid or plausibly exogenous external instruments, using inequalities when exact exogeneity is relaxed.',
    primaryEvidence(
      'braun-brueggemann-2023',
      'Abstract and Sections 2.2&ndash;2.3',
      'The paper combines signs with valid instruments in one setting and replaces exact proxy exogeneity by inequality bounds for plausibly exogenous instruments in another.',
      'https://doi.org/10.1080/07350015.2022.2104857',
      'Published-online 2022 manuscript underlying JBES 41(4), 2023',
    ),
    '2026-07-19',
  ),
  'sign.inference.rrwz': pageClaim(
    'sign',
    'sign.inference.rrwz',
    'literatureSections.2.body',
    'Rubio-Ram&iacute;rez, Waggoner, and Zha (2010, Theorem 9 and Algorithm 2) generate Haar-uniform orthogonal matrices by applying a QR decomposition to a standard-normal matrix, normalizing the diagonal of the triangular factor, and retaining rotations that satisfy the signs.',
    primaryEvidence(
      'rubio-ramirez-waggoner-zha-2010',
      'Section 6.4, Theorem 9 and Algorithm 2',
      'Theorem 9 establishes the Haar law for the normalized Gaussian QR factor; Algorithm 2 applies it and rejects rotations whose impulse responses violate the signs.',
      'raw/rubio-ramirez-waggoner-zha-2010-svar-identification/77-2-665.md',
      'Review of Economic Studies 77(2), 2010',
    ),
    '2026-07-19',
  ),
  'sign.inference.arias': pageClaim(
    'sign',
    'sign.inference.arias',
    'literatureSections.2.body',
    'Arias, Rubio-Ram&iacute;rez, and Waggoner (2018, Sections 3.5&ndash;3.6) draw rotations conditional on exact zero restrictions before filtering by signs because the equality-restricted set has measure zero among unrestricted draws.',
    primaryEvidence(
      'arias-rubio-ramirez-waggoner-2018',
      'Sections 3.5&ndash;3.6, especially Algorithm 3 and Theorem 4',
      'The paper states that unrestricted accept-reject sampling cannot reach the measure-zero zero-restriction set and constructs Haar-uniform rotation draws conditional on the exact zeros before applying signs.',
      'raw/arias-2014-sign-zero-svar-inference/Arias Ruboio-Ramirez Waggoner 2014 - Inference based on SVAR identified with sign and zero restrictions theory and applications.md',
      '2014 Federal Reserve working-paper text underlying Econometrica 86(2), 2018',
    ),
    '2026-07-19',
  ),
  'sign.reporting.kilian-lutkepohl': pageClaim(
    'sign',
    'sign.reporting.kilian-lutkepohl',
    'literatureSections.2.body',
    'Kilian and L&uuml;tkepohl (2017, Chapter 13, Section 13.6.3) show that pointwise posterior median responses generally need not correspond to any one admissible structural model.',
    primaryEvidence(
      'kilian-lutkepohl-2017',
      'Chapter 13, Section 13.6.3, pp. 396&ndash;401',
      'The chapter demonstrates that horizon-by-horizon posterior medians can select ordinates from different admissible models, producing a response path generated by no single structural model.',
      'raw/kilian-2016-structural-var-analysis-chapter-13-identification-by-sign-restrictions/SVARch13.md',
      'Cambridge University Press book chapter, 2017 edition',
    ),
    '2026-07-19',
  ),
  'narrative.origins.romer-romer-1989': pageClaim(
    'narrative',
    'narrative.origins.romer-romer-1989',
    'literatureSections.0.body',
    'Romer and Romer (1989, Abstract and Sections 2&ndash;3) use FOMC minutes and Records of Policy Actions to identify six episodes in which the Federal Reserve deliberately attempted to create a recession to reduce inflation.',
    primaryEvidence(
      'romer-romer-1989',
      'Abstract; Sections 2&ndash;3, especially pp. 134&ndash;138',
      'The authors describe reading FOMC minutes and Records of Policy Actions and identify six episodes in which the Federal Reserve decided to attempt to create a recession to reduce inflation.',
      'https://eml.berkeley.edu/~cromer/Reprints/MacroAnnual1989.pdf',
      'NBER Macroeconomics Annual 4, 1989',
    ),
    '2026-07-19',
  ),
  'narrative.origins.romer-romer-2010': pageClaim(
    'narrative',
    'narrative.origins.romer-romer-2010',
    'literatureSections.0.body',
    'Romer and Romer (2010, Abstract and Sections I&ndash;II) use primary policy records to classify legislated tax changes by motivation and retain inherited-deficit and long-run changes as unrelated to current or prospective economic conditions.',
    primaryEvidence(
      'romer-romer-2010',
      'Abstract; Sections I&ndash;II, especially pp. 763&ndash;772',
      'The paper uses contemporaneous executive and legislative records to classify tax actions and treats inherited-deficit and long-run actions as unrelated to current or prospective economic conditions.',
      'raw/romer-romer-2010-macroeconomic-effects-tax-changes/2010-the-macroeconomic-effects-of-tax-changes-estimates-based-on-a-new-measure-of-fiscal-shocks.md',
      'American Economic Review 100(3), 2010',
    ),
    '2026-07-19',
  ),
  'narrative.origins.ramey': pageClaim(
    'narrative',
    'narrative.origins.ramey',
    'literatureSections.0.body',
    'Ramey (2011, Abstract and Sections IV&ndash;V) shows that military dates and professional forecasts Granger-cause VAR spending shocks and constructs a defense-news series from contemporaneous reports to date changes in expected spending.',
    primaryEvidence(
      'ramey-2011',
      'Abstract; Sections IV&ndash;V, especially pp. 14&ndash;27',
      'The paper reports that military dates and professional forecasts predict VAR spending shocks and builds a defense-news measure from Business Week and newspaper reports about expected future spending.',
      'raw/ramey-2011-identifying-government-spending-shocks/qjq008.md',
      'Quarterly Journal of Economics 126(1), 2011',
    ),
    '2026-07-19',
  ),
  'narrative.origins.kilian': pageClaim(
    'narrative',
    'narrative.origins.kilian',
    'literatureSections.0.body',
    'Kilian (2008, Abstract) proposes a new measure of exogenous oil-supply shocks and finds that only a small fraction of oil-price increases during crisis episodes is attributable to exogenous production disruptions.',
    primaryEvidence(
      'kilian-2008-oil-supply',
      'Abstract',
      'The abstract introduces a new measure of exogenous oil-supply shocks and states that exogenous production disruptions account for only a small fraction of observed oil-price increases during oil-crisis periods.',
      'https://direct.mit.edu/rest/article-pdf/90/2/216/1614536/rest.90.2.216.pdf',
      'Review of Economics and Statistics 90(2), 2008',
    ),
    '2026-07-19',
  ),
  'narrative.variants.shock-sign': pageClaim(
    'narrative',
    'narrative.variants.shock-sign',
    'literatureSections.1.body',
    'Antol&iacute;n-D&iacute;az and Rubio-Ram&iacute;rez (2018, Section II.B) define narrative shock-sign restrictions that require a named recovered structural shock to be positive or negative at selected dates.',
    primaryEvidence(
      'antolin-diaz-rubio-ramirez-2018',
      'Section II.B, pp. 2807&ndash;2808',
      'Section II.B defines restrictions on the sign of a selected recovered structural shock at one or more specified observations.',
      'raw/antolindiaz-2018-narrative-sign-restrictions/AntolnDaz-NarrativeSignRestrictions-2018.md',
      'American Economic Review 108(10), 2018',
    ),
    '2026-07-19',
  ),
  'narrative.variants.historical-decomposition': pageClaim(
    'narrative',
    'narrative.variants.historical-decomposition',
    'literatureSections.1.body',
    'In Section II.C, they define Type A historical-decomposition restrictions by comparing one shock with each competing contribution and Type B restrictions by comparing it with the sum of all competing contributions.',
    primaryEvidence(
      'antolin-diaz-rubio-ramirez-2018',
      'Section II.C, pp. 2808&ndash;2810',
      'The paper labels pairwise most/least-important comparisons as Type A and comparisons with the sum of all other absolute contributions as Type B.',
      'raw/antolindiaz-2018-narrative-sign-restrictions/AntolnDaz-NarrativeSignRestrictions-2018.md',
      'American Economic Review 108(10), 2018',
    ),
    '2026-07-19',
  ),
  'narrative.applications.antolin-diaz': pageClaim(
    'narrative',
    'narrative.applications.antolin-diaz',
    'literatureSections.2.body',
    'Antol&iacute;n-D&iacute;az and Rubio-Ram&iacute;rez (2018, Abstract and Sections IV&ndash;V) use narrative restrictions around the August 1990 Persian Gulf War and the October 1979 Volcker reform and show that even one event can sharply narrow the admissible structural set.',
    primaryEvidence(
      'antolin-diaz-rubio-ramirez-2018',
      'Abstract; Sections IV&ndash;V, especially pp. 2814&ndash;2826',
      'The oil application shows that August 1990 alone sharply sharpens identification, while the monetary application uses October 1979 to discard historically implausible rotations and alter inference.',
      'raw/antolindiaz-2018-narrative-sign-restrictions/AntolnDaz-NarrativeSignRestrictions-2018.md',
      'American Economic Review 108(10), 2018',
    ),
    '2026-07-19',
  ),
  'narrative.applications.ludvigson-ma-ng': pageClaim(
    'narrative',
    'narrative.applications.ludvigson-ma-ng',
    'literatureSections.2.body',
    'Ludvigson, Ma, and Ng (2021, Sections III.B&ndash;III.C) restrict recovered shocks at selected historical events and impose signed-correlation inequalities with stock returns and real gold-price changes, explicitly without treating those external variables as valid instruments.',
    primaryEvidence(
      'ludvigson-ma-ng-2021',
      'Sections III.B&ndash;III.C, especially pp. 378&ndash;386',
      'The paper combines event constraints on recovered shocks with negative stock-return and positive real-gold-price correlation inequalities and states that the external variables need not be valid exogenous instruments.',
      'raw/ludvigson-2021-uncertainty-business-cycles/Ludvigson_Ma_Ng_AEJM.md',
      'American Economic Journal: Macroeconomics 13(4), 2021',
    ),
    '2026-07-19',
  ),
  'narrative.inference.antolin-diaz': pageClaim(
    'narrative',
    'narrative.inference.antolin-diaz',
    'literatureSections.3.body',
    'Antol&iacute;n-D&iacute;az and Rubio-Ram&iacute;rez (2018, Section III, equation (17), and Algorithm 1) show that narrative restrictions truncate the likelihood and weight accepted draws by the inverse model-implied probability of satisfying the event.',
    primaryEvidence(
      'antolin-diaz-rubio-ramirez-2018',
      'Section III, equation (17), and Algorithm 1, pp. 2810&ndash;2813',
      'Equation (17) expresses the narrative-restricted likelihood with an inverse event-probability factor, and Algorithm 1 assigns accepted draws the corresponding inverse-probability importance weight.',
      'raw/antolindiaz-2018-narrative-sign-restrictions/AntolnDaz-NarrativeSignRestrictions-2018.md',
      'American Economic Review 108(10), 2018',
    ),
    '2026-07-19',
  ),
  'long-run.origins.blanchard-quah': pageClaim(
    'long-run',
    'long-run.origins.blanchard-quah',
    'literatureSections.0.body',
    'Blanchard and Quah (1989, Sections I&ndash;II) model U.S. output growth and unemployment and identify a demand disturbance by imposing that it has no long-run effect on the level of output.',
    primaryEvidence(
      'blanchard-quah-1989',
      'Sections I&ndash;II, especially pp. 4&ndash;10 of NBER Working Paper 2737',
      'The bivariate model uses output growth and unemployment and imposes that the first structural disturbance has no long-run effect on the output level before labeling it demand.',
      'raw/blanchard-quah-1988-demand-supply-disturbances/w2737.md',
      'NBER Working Paper 2737 (1988), primary version underlying AER 79(4), 1989',
    ),
    '2026-07-19',
  ),
  'long-run.identification.blanchard-quah': pageClaim(
    'long-run',
    'long-run.identification.blanchard-quah',
    'literatureSections.0.body',
    'The covariance restrictions plus this zero identify the two structural shocks without requiring a recursive impact matrix.',
    primaryEvidence(
      'blanchard-quah-1989',
      'Sections I&ndash;II and Appendix A',
      'The covariance matrix supplies three restrictions and the long-run output zero supplies the fourth; the restriction concerns cumulative effects rather than a triangular impact response.',
      'raw/blanchard-quah-1988-demand-supply-disturbances/w2737.md',
      'NBER Working Paper 2737 (1988), primary version underlying AER 79(4), 1989',
    ),
    '2026-07-19',
  ),
  'long-run.stationary.kilian-lutkepohl': pageClaim(
    'long-run',
    'long-run.stationary.kilian-lutkepohl',
    'literatureSections.1.body',
    'Kilian and L&uuml;tkepohl (2017, Chapter 10, Section 10.2) show that a triangular long-run multiplier in a stationary VAR can be recovered from a Cholesky factorization of the long-run covariance and then mapped back to a generally nonrecursive impact matrix.',
    primaryEvidence(
      'kilian-lutkepohl-2017',
      'Chapter 10, Section 10.2, especially equations (10.1)&ndash;(10.7)',
      'The chapter factors the long-run covariance under a triangular long-run restriction and recovers the contemporaneous structural mapping from the VAR polynomial and that long-run factor.',
      'raw/kilian-2016-structural-var-analysis-chapter-10-identification-by-long-run-restrictions/SVARch10.md',
      'Cambridge University Press book chapter, 2017 edition',
    ),
    '2026-07-19',
  ),
  'long-run.cointegration.kilian-lutkepohl': pageClaim(
    'long-run',
    'long-run.cointegration.kilian-lutkepohl',
    'literatureSections.1.body',
    'In cointegrated systems, Section 10.3 shows that the common-trend multiplier has rank K&minus;r, so zeros implied by stationarity or rank add no identifying information and long-run restrictions can leave transitory shocks unresolved.',
    primaryEvidence(
      'kilian-lutkepohl-2017',
      'Chapter 10, Section 10.3, especially equations (10.8)&ndash;(10.19)',
      'The VECM common-trend multiplier has rank K-r; stationary rows and transitory columns can be zero mechanically, and additional short-run information may be needed to distinguish multiple transitory shocks.',
      'raw/kilian-2016-structural-var-analysis-chapter-10-identification-by-long-run-restrictions/SVARch10.md',
      'Cambridge University Press book chapter, 2017 edition',
    ),
    '2026-07-19',
  ),
  'long-run.applications.kpsw': pageClaim(
    'long-run',
    'long-run.applications.kpsw',
    'literatureSections.2.body',
    'King, Plosser, Stock, and Watson (1991, Abstract and Sections I&ndash;II) identify permanent productivity shocks with the common stochastic trend in output, consumption, and investment.',
    primaryEvidence(
      'king-plosser-stock-watson-1991',
      'Abstract and Sections I&ndash;II, pp. 819&ndash;829',
      'The paper uses the cointegrating common trend in output, consumption, and investment as the permanent productivity shock implied by balanced-growth models.',
      'https://www.princeton.edu/~mwatson/papers/King_Plosser_Stock_Watson_AER_1991.pdf',
      'American Economic Review 81(4), 1991',
    ),
    '2026-07-19',
  ),
  'long-run.applications.gali': pageClaim(
    'long-run',
    'long-run.applications.gali',
    'literatureSections.2.body',
    'Gal&iacute; (1999, Abstract and Section II) identifies technology shocks by assuming that only they can permanently affect labor productivity and finds that hours decline persistently after a positive technology shock.',
    primaryEvidence(
      'gali-1999',
      'Abstract and Section II, especially pp. 256&ndash;258',
      'Section II imposes that the productivity unit root originates only in technology shocks, and the abstract reports a persistent decline in hours after a positive technology shock.',
      'https://crei.cat/wp-content/uploads/2016/07/gali_aer1999.pdf',
      'American Economic Review 89(1), 1999',
    ),
    '2026-07-19',
  ),
  'long-run.applications.beaudry-portier': pageClaim(
    'long-run',
    'long-run.applications.beaudry-portier',
    'literatureSections.2.body',
    'Beaudry and Portier (2006, Abstract and Sections I&ndash;II) identify a shock that moves stock prices immediately but affects productivity only with a substantial delay and interpret it as news about future technology.',
    primaryEvidence(
      'beaudry-portier-2006',
      'Abstract and Sections I&ndash;II',
      'The paper reports a structural shock with no short-run productivity effect but a delayed productivity effect, first captured in stock prices, and offers news about future technology as its interpretation.',
      'https://www.aeaweb.org/articles?id=10.1257/aer.96.4.1293',
      'American Economic Review 96(4), 2006',
    ),
    '2026-07-19',
  ),
  'long-run.limits.kurmann-mertens': pageClaim(
    'long-run',
    'long-run.limits.kurmann-mertens',
    'literatureSections.2.body',
    'Kurmann and Mertens (2014, Abstract and Section I) show that this identification is not unique in the Beaudry&ndash;Portier VECMs with more than two variables because of the interaction between cointegration and long-run restrictions.',
    primaryEvidence(
      'kurmann-mertens-2014',
      'Abstract and Section I',
      'The comment states that the Beaudry-Portier identification has no unique solution in VECMs with more than two variables because of the interplay between cointegration assumptions and long-run restrictions.',
      'https://www.aeaweb.org/articles?id=10.1257/aer.104.4.1439',
      'American Economic Review 104(4), 2014',
    ),
    '2026-07-19',
  ),
  'long-run.limits.faust-leeper': pageClaim(
    'long-run',
    'long-run.limits.faust-leeper',
    'literatureSections.3.body',
    'Faust and Leeper (1997, Sections 2&ndash;4) show that long-run identification can be unreliable because long-run effects are imprecisely estimated and because aggregation across variables or time can mix the underlying structural shocks.',
    primaryEvidence(
      'faust-leeper-1997',
      'Sections 2&ndash;4, pp. 347&ndash;352',
      'The article analyzes finite-sample imprecision in long-run effects, multiple-shock aggregation in low-dimensional VARs, and time aggregation as three sources of unreliable structural inference.',
      'https://uva.theopenscholar.com/files/eric-leeper/files/faustleeper_jbes1997.pdf',
      'Journal of Business & Economic Statistics 15(3), 1997',
    ),
    '2026-07-19',
  ),
  'max-share.origins.uhlig': pageClaim(
    'max-share',
    'max-share.origins.uhlig',
    'literatureSections.0.body',
    'Uhlig (2004, Abstract) searches for two VAR shocks that together explain most of real GNP\'s k-step prediction-error variance over horizons from zero to five years.',
    primaryEvidence(
      'uhlig-2004',
      'Abstract',
      'The public paper record states that the VAR search selects two shocks that explain the majority of real-GNP k-step prediction-error variances at horizons between zero and five years.',
      'https://ideas.repec.org/p/ecm/nawm04/636.html',
      'Econometric Society 2004 North American Winter Meetings paper record supplied through RePEc',
    ),
    '2026-07-19',
  ),
  'max-share.origins.barsky-sims': pageClaim(
    'max-share',
    'max-share.origins.barsky-sims',
    'literatureSections.0.body',
    'Barsky and Sims (2011, Abstract and Section 2.1) identify a technology-news shock that is orthogonal to the current TFP innovation and maximizes the sum of its contributions to future TFP forecast-error variance over a finite horizon.',
    primaryEvidence(
      'barsky-sims-2011',
      'Abstract; Section 2.1, pp. 1–5',
      'The paper imposes no contemporaneous TFP response to the news shock and selects the orthogonal direction that maximizes the sum of its TFP forecast-error-variance contributions through a finite horizon.',
      'https://sites.nd.edu/esims/files/2023/05/barsky_sims_news_final.pdf',
      'Author-hosted February 2011 article manuscript',
    ),
    '2026-07-19',
  ),
  'max-share.sequential.caldara': pageClaim(
    'max-share',
    'max-share.sequential.caldara',
    'literatureSections.1.body',
    'Caldara, Fuentes-Albero, Gilchrist, and Zakrajsek (2016, Sections 1 and 3.1) first choose an uncertainty shock by maximizing its target proxy\'s response over a prespecified horizon, then choose an orthogonal financial shock by maximizing the response of a financial-conditions indicator over the same horizon.',
    primaryEvidence(
      'caldara-et-al-2016',
      'Section 1, pp. 187–188; Section 3.1',
      'The paper describes a two-step penalty-function procedure: maximize the uncertainty proxy response first, then maximize the financial-conditions response over the same horizon subject to orthogonality to the first shock.',
      'raw/caldara-2016-financial-uncertainty-shocks/1-s2.0-S0014292116300393-main.md',
      'European Economic Review 88, 2016',
    ),
    '2026-07-19',
  ),
  'max-share.sequential.caldara-reverse': pageClaim(
    'max-share',
    'max-share.sequential.caldara-reverse',
    'literatureSections.1.body',
    'They also repeat the two penalty-function steps in the reverse order.',
    primaryEvidence(
      'caldara-et-al-2016',
      'Section 1, p. 188; Section 3.2',
      'The paper explicitly treats reversing the order of the uncertainty and financial penalty-function searches as an alternative identification strategy.',
      'raw/caldara-2016-financial-uncertainty-shocks/1-s2.0-S0014292116300393-main.md',
      'European Economic Review 88, 2016',
    ),
    '2026-07-19',
  ),
  'max-share.joint.carriero-volpicella': pageClaim(
    'max-share',
    'max-share.joint.carriero-volpicella',
    'literatureSections.1.body',
    'Carriero and Volpicella (2025, Section 3.1) instead jointly maximize a forecast-error-variance objective over several orthonormal shock directions.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 3.1, equations 3.1 and 3.4',
      'The proposed estimator maximizes the sum of target-variable forecast-error-variance contributions over k shock vectors while constraining those vectors to be orthonormal.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'max-share.joint.dominance': pageClaim(
    'max-share',
    'max-share.joint.dominance',
    'literatureSections.2.body',
    'Carriero and Volpicella (2025, equation 3.2) require each selected shock to contribute more to the forecast-error variance of its own target than to the variances of the other target variables.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 3.1, equation 3.2',
      'For every selected shock, the inequality compares its quadratic forecast-error-variance contribution to its designated target with its contribution to every other target and requires the former to be no smaller.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'max-share.joint.nonempty': pageClaim(
    'max-share',
    'max-share.joint.nonempty',
    'literatureSections.2.body',
    'Their Proposition 3.2 gives a sufficient condition for the constrained joint problem to be non-empty.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 3.1, Proposition 3.2',
      'Proposition 3.2 supplies sufficient sequential-nullspace conditions under which an orthogonal matrix satisfying the joint constraints exists.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'max-share.joint.unique': pageClaim(
    'max-share',
    'max-share.joint.unique',
    'literatureSections.2.body',
    'Their Proposition 3.3 gives a sufficient condition for a feasible solution to be unique when the relevant target responses satisfy the stated sign restrictions.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 3.1, Proposition 3.3',
      'Conditional on existence, Proposition 3.3 states that nonnegative responses of the target variables to the selected shocks through the objective horizon are sufficient for a unique solution.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'max-share.implementation.bayesian': pageClaim(
    'max-share',
    'max-share.implementation.bayesian',
    'literatureSections.3.body',
    'Carriero and Volpicella\'s (2025, Algorithm 3.1) Bayesian implementation draws reduced-form VAR parameters, checks that the constrained problem is non-empty, solves the joint optimization, and repeats those steps.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 3.2, Algorithm 3.1',
      'The algorithm draws reduced-form parameters from their posterior, checks feasibility, solves the constrained joint objective, computes structural objects, and repeats the sequence.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'max-share.implementation.frequentist': pageClaim(
    'max-share',
    'max-share.implementation.frequentist',
    'literatureSections.3.body',
    'They note that maximum-likelihood or bootstrap draws can replace posterior draws.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 3.2, paragraph following Algorithm 3.1',
      'The authors state that the first step can use maximum-likelihood estimates with large-sample inference or bootstrap coefficient draws because the later optimization conditions on the reduced-form parameters.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'max-share.limits.confounding': pageClaim(
    'max-share',
    'max-share.limits.confounding',
    'literatureSections.4.body',
    'Carriero and Volpicella (2025, Example 2.1) show analytically how standard one-at-a-time max-share can produce a linear combination of the data-generating shocks.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 2.2, Example 2.1',
      'The bivariate example derives the individually selected max-share shock as a rotation, hence generally a linear combination, of the two data-generating shocks unless a special full-share condition holds.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'max-share.limits.simulation': pageClaim(
    'max-share',
    'max-share.limits.simulation',
    'literatureSections.4.body',
    'Their Section 3.3 simulations compare that procedure with joint identification.',
    primaryEvidence(
      'carriero-volpicella-2025',
      'Section 3.3 and Figures C.5–C.7',
      'The Monte Carlo exercises compare standard single-shock max-share with the proposed joint scheme in data-generating processes featuring uncertainty and financial shocks.',
      'raw/carriero-2025-max-share-multiple-shocks/Max Share Identification of Multiple Shocks An Application to Uncertainty and Financial Conditions.md',
      'Journal of Business & Economic Statistics 43(1), 2025',
    ),
    '2026-07-19',
  ),
  'proxy.origins.stock-watson': pageClaim(
    'proxy',
    'proxy.origins.stock-watson',
    'literatureSections.0.body',
    'Stock and Watson (2012, Section III) use 17 external instruments to estimate six structural shocks in a dynamic factor model.',
    primaryEvidence(
      'stock-watson-2012',
      'Introduction, especially p. 83; Section III',
      'The paper states that it uses 17 shock measures constructed elsewhere as external instruments to estimate six structural shocks in its dynamic factor model.',
      'https://www.brookings.edu/wp-content/uploads/2012/03/2012a_Stock.pdf',
      'Brookings Papers on Economic Activity, Spring 2012',
    ),
    '2026-07-19',
  ),
  'proxy.origins.mertens-ravn': pageClaim(
    'proxy',
    'proxy.origins.mertens-ravn',
    'literatureSections.0.body',
    'Mertens and Ravn (2013, Abstract and Section I.A) treat narratively identified personal- and corporate-tax changes as proxies for latent tax shocks that may be measured with error.',
    primaryEvidence(
      'mertens-ravn-2013',
      'Abstract, Introduction, and Section I.A',
      'The authors use narratively identified tax changes as proxies for latent personal and corporate tax shocks and motivate the estimator by measurement error in narrative measures.',
      'raw/mertens-2013-narrative-proxy-svar-tax-shocks/2013-the-dynamic-effects-of-personal-and-corporate-income-tax-changes-in-the-united-states.md',
      'American Economic Review 103(4), 2013',
    ),
    '2026-07-19',
  ),
  'proxy.estimator.kilian-lutkepohl': pageClaim(
    'proxy',
    'proxy.estimator.kilian-lutkepohl',
    'literatureSections.0.body',
    'Kilian and L&uuml;tkepohl (2017, Chapter 15, Section 15.2.1) show that relevance and exclusion make the proxy&ndash;residual covariance vector proportional to the target shock\'s impact vector, which identifies its direction after normalization.',
    primaryEvidence(
      'kilian-lutkepohl-2017',
      'Chapter 15, Section 15.2.1, especially equations (15.2.1)&ndash;(15.2.2)',
      'The chapter derives E(z_t u_t)=a theta_{1,0} from relevance and exclusion and identifies the normalized target impact vector from this covariance.',
      'raw/kilian-2016-structural-var-analysis-chapter-15-identification-based-on-extraneous-data/SVARch15.md',
      'Cambridge University Press book chapter, 2017 edition',
    ),
    '2026-07-19',
  ),
  'proxy.inference.mosw': pageClaim(
    'proxy',
    'proxy.inference.mosw',
    'literatureSections.1.body',
    'Montiel Olea, Stock, and Watson (2021, Sections 3&ndash;4) construct Anderson&ndash;Rubin/Fieller confidence sets for impulse responses that remain valid when the external instrument is weak and coincide with standard intervals when it is strong.',
    primaryEvidence(
      'montiel-olea-stock-watson-2021',
      'Sections 3&ndash;4, especially Section 4.1',
      'The paper develops Fieller/Anderson-Rubin confidence sets for impulse responses, proves validity under weak instruments, and notes that they coincide with standard intervals under strong instruments.',
      'raw/montielolea-2021-svar-iv-weak-instrument/1-s2.0-S0304407620302311-main.md',
      'Journal of Econometrics 225(1), 2021',
    ),
    '2026-07-19',
  ),
  'proxy.identification.miranda-agrippino-ricco': pageClaim(
    'proxy',
    'proxy.identification.miranda-agrippino-ricco',
    'literatureSections.1.body',
    'Miranda-Agrippino and Ricco (2023, Sections 2&ndash;6) show that full-system invertibility is unnecessary, but the target shock must be partially invertible and the instrument must satisfy limited lead&ndash;lag exogeneity.',
    primaryEvidence(
      'miranda-agrippino-ricco-2023',
      'Sections 2&ndash;6 and conclusion',
      'The paper replaces full invertibility with partial invertibility of the target shock and derives limited lead-lag exogeneity as the additional instrument condition for correct identification.',
      'raw/mirandaagrippino-2023-external-instruments-partial-invertibility/1-s2.0-S0304393223000132-main.md',
      'Journal of Monetary Economics 135, 2023',
    ),
    '2026-07-19',
  ),
  'proxy.identification.angelini': pageClaim(
    'proxy',
    'proxy.identification.angelini',
    'literatureSections.1.body',
    'Angelini, Cavaliere, and Fanelli (2024, Abstract and Sections 2&ndash;6) show that target responses can instead be estimated by minimum distance from strong proxies for non-target shocks when their identification conditions hold.',
    primaryEvidence(
      'angelini-cavaliere-fanelli-2024',
      'Abstract and Sections 2&ndash;6',
      'The paper develops an indirect minimum-distance strategy that uses strong instruments for non-target shocks to recover target-shock responses subject to its order and rank conditions.',
      'raw/angelini-2024-weak-proxy-svar/1-s2.0-S0304407623003202-main.md',
      'Journal of Econometrics 238(2), article 105604, 2024',
    ),
    '2026-07-19',
  ),
  'proxy.bootstrap.jentsch-lunsford-2019': pageClaim(
    'proxy',
    'proxy.bootstrap.jentsch-lunsford-2019',
    'literatureSections.2.body',
    'Jentsch and Lunsford (2019, Abstract and Sections I&ndash;II) show that the wild bootstrap used by Mertens and Ravn is invalid for Proxy-SVAR impulse responses and produces confidence intervals that are too small.',
    primaryEvidence(
      'jentsch-lunsford-2019',
      'Abstract and Sections I&ndash;II',
      'The comment explains why the residual-based wild bootstrap fails for Proxy-SVAR impulse responses and reports that its confidence intervals are much too small.',
      'raw/jentsch-2019-proxy-svar-mbb-bootstrap/jentsch_aer.md',
      'American Economic Review 109(7), 2019',
    ),
    '2026-07-19',
  ),
  'proxy.bootstrap.jentsch-lunsford-2022': pageClaim(
    'proxy',
    'proxy.bootstrap.jentsch-lunsford-2022',
    'literatureSections.2.body',
    'Jentsch and Lunsford (2022, Abstract and Sections 1&ndash;4) prove validity of a modified residual-based moving-block bootstrap for smooth Proxy-SVAR statistics under strong proxies.',
    primaryEvidence(
      'jentsch-lunsford-2022',
      'Abstract and Sections 1&ndash;4',
      'The paper proves asymptotic validity of a residual-based moving-block bootstrap that jointly resamples VAR innovations and proxies for smooth statistics when the proxies are strong.',
      'raw/jentsch-2022-bootstrap-proxy-svars/Asymptotically Valid Bootstrap Inference for Proxy SVARs.md',
      'Journal of Business & Economic Statistics 40(4), 2022',
    ),
    '2026-07-19',
  ),
  'proxy.bootstrap.bruns-lutkepohl': pageClaim(
    'proxy',
    'proxy.bootstrap.bruns-lutkepohl',
    'literatureSections.2.body',
    'Bruns and L&uuml;tkepohl (2023, Abstract and Section 1) propose a proxy-residual-based bootstrap whose simulated confidence intervals often have more accurate coverage than moving-block intervals of similar length.',
    primaryEvidence(
      'bruns-lutkepohl-2023',
      'Abstract and Section 1',
      'The paper proposes the proxy-residual-based bootstrap and reports simulations in which its impulse-response intervals often have more precise coverage and similar length relative to moving-block intervals.',
      'raw/bruns-2022-alternative-bootstrap-proxy-var/An_Alternative_Bootstrap_for_Proxy_Vector_Autoregr.md',
      'Computational Economics 62(4), 2023',
    ),
    '2026-07-19',
  ),
  'proxy.bayesian.arias': pageClaim(
    'proxy',
    'proxy.bayesian.arias',
    'literatureSections.2.body',
    'Arias, Rubio-Ram&iacute;rez, and Waggoner (2021, Abstract and Section 1) develop an exact finite-sample Bayesian algorithm that makes independent posterior draws and can combine proxies with zero and sign restrictions.',
    primaryEvidence(
      'arias-rubio-ramirez-waggoner-2021',
      'Abstract and Section 1',
      'The paper develops an exact finite-sample algorithm for independent posterior draws in Proxy-SVARs and explicitly allows proxy restrictions to be combined with zero and sign restrictions.',
      'raw/arias-2021-bayesian-proxy-svar/1-s2.0-S0304407620303985-main.md',
      'Journal of Econometrics 225(1), 2021',
    ),
    '2026-07-19',
  ),
  'proxy.bayesian.giacomini-kitagawa-read': pageClaim(
    'proxy',
    'proxy.bayesian.giacomini-kitagawa-read',
    'literatureSections.2.body',
    'Giacomini, Kitagawa, and Read (2022, Abstract and Section 1) extend multiple-prior robust Bayesian inference to set-identified Proxy-SVARs so results need not depend on one unrevisable prior over admissible rotations.',
    primaryEvidence(
      'giacomini-kitagawa-read-2022',
      'Abstract and Section 1',
      'The paper extends robust Bayesian inference to set-identified Proxy-SVARs by considering a class of priors over the set-identified rotation rather than selecting one unrevisable prior.',
      'raw/giacomini-2022-robust-bayesian-proxy-svar/1-s2.0-S0304407621000518-main.md',
      'Journal of Econometrics 228(1), 2022',
    ),
    '2026-07-19',
  ),
  'proxy.applications.gertler-karadi': pageClaim(
    'proxy',
    'proxy.applications.gertler-karadi',
    'literatureSections.3.body',
    'Gertler and Karadi (2015, Abstract and Introduction) use high-frequency interest-rate surprises around policy announcements as external instruments in monetary VARs.',
    primaryEvidence(
      'gertler-karadi-2015',
      'Abstract and Introduction',
      'The paper combines high-frequency policy surprises with VAR analysis and explicitly uses the surprises as external instruments to identify monetary-policy shocks.',
      'raw/gertler-karadi-2015-monetary-policy-surprises/gertler-karadi-2015-monetary-policy-surprises-credit-costs-and-economic-activity.md',
      'American Economic Journal: Macroeconomics 7(1), 2015',
    ),
    '2026-07-19',
  ),
  'proxy.applications.jarocinski-karadi': pageClaim(
    'proxy',
    'proxy.applications.jarocinski-karadi',
    'literatureSections.3.body',
    'Jaroci&nacute;ski and Karadi (2020, Abstract and Introduction) separate policy and central-bank-information shocks by the sign of the announcement-window co-movement between interest rates and stock prices.',
    primaryEvidence(
      'jarocinski-karadi-2020',
      'Abstract and Introduction',
      'The paper identifies a policy tightening by higher rates and lower stock prices and an information shock by higher rates and higher stock prices in narrow announcement windows.',
      'raw/jarocinski-karadi-2020-deconstructing-monetary-policy-surprises/Jarocinski Karadi 2020.md',
      'American Economic Journal: Macroeconomics 12(2), 2020',
    ),
    '2026-07-19',
  ),
  'proxy.applications.kanzig-oil': pageClaim(
    'proxy',
    'proxy.applications.kanzig-oil',
    'literatureSections.3.body',
    'K&auml;nzig (2021, Abstract and Introduction) uses oil-futures movements around OPEC announcements as an external instrument for an oil-supply-news shock.',
    primaryEvidence(
      'kanzig-2021-oil-supply-news',
      'Abstract and Introduction',
      'The paper constructs high-frequency oil-futures surprises around OPEC announcements and uses the resulting series as an external instrument for a structural oil-supply-news shock.',
      'https://doi.org/10.1257/aer.20190964',
      'American Economic Review 111(4), 2021',
    ),
    '2026-07-19',
  ),
  'proxy.applications.kanzig-carbon': pageClaim(
    'proxy',
    'proxy.applications.kanzig-carbon',
    'literatureSections.3.body',
    'K&auml;nzig (2023, revised 2025, Abstract and Section 1) instruments a carbon-policy shock with EU ETS regulatory-event surprises measured in carbon futures prices.',
    primaryEvidence(
      'kanzig-2023-carbon-pricing-r2025',
      'Abstract and Section 1 of the September 2025 revision',
      'The paper measures carbon-policy surprises from changes in EUA futures prices around EU ETS regulatory events and uses the surprise series as an instrument for a latent carbon-policy shock.',
      'raw/kanzig-2026-unequal-economic-consequences-carbon-pricing/kaenzig_jmp_unequal_consequences_carbon_pricing.md',
      'NBER Working Paper 31221, issued May 2023, September 2025 revision',
    ),
    '2026-07-19',
  ),
  'proxy.extensions.braun-brueggemann': pageClaim(
    'proxy',
    'proxy.extensions.braun-brueggemann',
    'literatureSections.3.body',
    'Braun and Br&uuml;ggemann (2023, Abstract and Section 1) combine valid or plausibly exogenous external instruments with sign restrictions in a Bayesian SVAR.',
    primaryEvidence(
      'braun-brueggemann-2023',
      'Abstract and Section 1',
      'The paper develops a Bayesian SVAR framework that combines sign restrictions with either valid external instruments or inequality restrictions for plausibly exogenous instruments.',
      'https://doi.org/10.1080/07350015.2022.2104857',
      'Journal of Business & Economic Statistics 41(4), 2023',
    ),
    '2026-07-19',
  ),
  'proxy.multiple.bruns-lutkepohl-mcneil': pageClaim(
    'proxy',
    'proxy.multiple.bruns-lutkepohl-mcneil',
    'literatureSections.3.body',
    'Bruns, L&uuml;tkepohl, and McNeil (2025, Abstract and Section 1) show that identifying several shocks one by one can leave them correlated and propose a joint GMM estimator that enforces shock orthogonality.',
    primaryEvidence(
      'bruns-lutkepohl-mcneil-2025',
      'Abstract and Section 1',
      'The paper shows that individually identified proxy shocks may be correlated and proposes a GMM estimator that imposes uncorrelatedness and supports a specification test.',
      'raw/bruns-2025-correlated-shocks-proxy-var/Avoiding Unintentionally Correlated Shocks in Proxy Vector Autoregressive Analysis.md',
      'Journal of Business & Economic Statistics 43(4), 2025',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.origins.sentana': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.origins.sentana',
    'literatureSections.0.body',
    'Sentana and Fiorentini (2001, Section 3.1, Proposition 3) show that when the loading covariance and idiosyncratic covariance are identified from unconditional moments and the factor-variance processes are linearly independent, the loading matrix is unique up to column signs and permutations.',
    primaryEvidence(
      'sentana-fiorentini-2001',
      'Section 3.1, Proposition 3',
      'Proposition 3 states that, once the unconditional factor-loading and idiosyncratic covariance components are identified, linear independence of the factor variance processes makes the loading matrix unique up to signs and permutations.',
      'raw/sentana-2001-heteroskedastic-factor-models/1-s2.0-S0304407601000513-main.md',
      'Journal of Econometrics 106(2), 2001',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.origins.rigobon': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.origins.rigobon',
    'literatureSections.0.body',
    'Rigobon (2003, Proposition 1) identifies a bivariate simultaneous-equation system from two variance regimes under stable structural slopes, uncorrelated shocks, and nonproportional covariance matrices.',
    primaryEvidence(
      'rigobon-2003',
      'Section II.A, Proposition 1, pp. 777-781',
      'Proposition 1 establishes identification in the two-equation, two-regime model when structural coefficients are stable, structural shocks are uncorrelated, and their relative variances change across regimes.',
      'raw/rigobon-2003-identification-through-heteroskedasticity/Rigobon-IdentificationHeteroskedasticity-2003.md',
      'Review of Economics and Statistics 85(4), 2003',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.limits.proportional': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.limits.proportional',
    'literatureSections.0.body',
    'His Section II.A also shows that proportional regime covariance matrices do not identify the system.',
    primaryEvidence(
      'rigobon-2003',
      'Section II.A, pp. 779-780',
      'The covariance equations are unchanged when all structural shock variances move by the same proportion, so a proportional covariance shift supplies no identifying variation.',
      'raw/rigobon-2003-identification-through-heteroskedasticity/Rigobon-IdentificationHeteroskedasticity-2003.md',
      'Review of Economics and Statistics 85(4), 2003',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.llm-model': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.llm-model',
    'literatureSections.1.body',
    'Lanne, L&uuml;tkepohl, and Maciejowska (2010, Abstract and Section 1) confine Markov switching to innovation covariances and assume that impulse responses are invariant across states.',
    primaryEvidence(
      'lanne-lutkepohl-maciejowska-2010',
      'Abstract and Section 1, pp. 121-123',
      'The paper introduces Markov switching in the innovation covariance matrix while keeping the VAR coefficients and contemporaneous impact relations, and therefore impulse responses, state invariant.',
      'raw/lanne-lutkepohl-maciejowska-2010-svar-markov-switching/Lanne Lütkepohl Maciejoswka2010 - Structural vector autoregressions with Markov switching.md',
      'Journal of Economic Dynamics and Control 34(2), 2010',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.llm-testing': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.llm-testing',
    'literatureSections.1.body',
    'They show that conventional just-identifying restrictions become testable.',
    primaryEvidence(
      'lanne-lutkepohl-maciejowska-2010',
      'Abstract and Section 1, pp. 121-123',
      'Identification from changes in covariance supplies additional information, so restrictions that would only just identify a conventional SVAR can instead be treated as overidentifying and tested.',
      'raw/lanne-lutkepohl-maciejowska-2010-svar-markov-switching/Lanne Lütkepohl Maciejoswka2010 - Structural vector autoregressions with Markov switching.md',
      'Journal of Economic Dynamics and Control 34(2), 2010',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.llm-state-invariance': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.llm-state-invariance',
    'literatureSections.1.body',
    'With more than two covariance states, they also test state-invariant impact responses.',
    primaryEvidence(
      'lanne-lutkepohl-maciejowska-2010',
      'Section 1, pp. 122-123',
      'The paper explains that models with more than two volatility states provide overidentifying information that can be used to test the maintained constancy of the structural impact relations across states.',
      'raw/lanne-lutkepohl-maciejowska-2010-svar-markov-switching/Lanne Lütkepohl Maciejoswka2010 - Structural vector autoregressions with Markov switching.md',
      'Journal of Economic Dynamics and Control 34(2), 2010',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.milunovich-yang': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.milunovich-yang',
    'literatureSections.1.body',
    'Milunovich and Yang (2013, Proposition 2) give sufficient conditions for joint local identification of the impact matrix and structural ARCH parameters when shocks are nondegenerate and at most one is homoskedastic.',
    primaryEvidence(
      'milunovich-yang-2013',
      'Proposition 2',
      'Proposition 2 gives sufficient rank and nondegeneracy conditions for local identification of the contemporaneous matrix and ARCH parameters, permitting no more than one structural innovation without ARCH variation.',
      'raw/milunovich-2013-svar-arch-effects/[19411928 - Journal of Time Series Econometrics] On Identifying Structural VAR Models via ARCH Effects.md',
      'Journal of Time Series Econometrics 5(2), 2013',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.lutkepohl-netsunajev': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.lutkepohl-netsunajev',
    'literatureSections.1.body',
    'L&uuml;tkepohl and Netsunajev (2017, Abstract and Section 1) model a gradual covariance transition whose timing is estimated rather than fixed by the researcher.',
    primaryEvidence(
      'lutkepohl-netsunajev-2017',
      'Abstract and Section 1',
      'The model lets innovation variances change smoothly between regimes and estimates the transition location and speed jointly with the other parameters rather than requiring an externally dated break.',
      'raw/lutkepohl-netsunajev-2017-svar-smooth-transition-variances/Lütkepohl Netsunajev 2017 - Structural vector autoregressions with smooth transition in variances.md',
      'Journal of Economic Dynamics and Control 84, 2017',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.lewis': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.lewis',
    'literatureSections.1.body',
    'Lewis (2021, Abstract and Theorems 1&ndash;3) identifies the impact matrix from autocovariances of squared reduced-form innovations without imposing a parametric law on the variance process.',
    primaryEvidence(
      'lewis-2021',
      'Abstract; Sections 2.2-2.3, Theorems 1-3',
      'The identification results use autocovariances of squared reduced-form innovations generated by time-varying volatility and do not specify a parametric stochastic-volatility or GARCH law.',
      'raw/lewis-2021-identifying-shocks-time-varying-volatility/Lewis.md',
      'Review of Economic Studies 88(6), 2021',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.lewis-rank': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.lewis-rank',
    'literatureSections.1.body',
    'He also provides reduced-form rank tests of the identifying conditions.',
    primaryEvidence(
      'lewis-2021',
      'Section 2.3, Proposition 2 and Theorem 3',
      'Lewis derives testable rank restrictions stated in reduced-form moments and develops tests for whether the volatility variation is sufficient to identify the structural directions.',
      'raw/lewis-2021-identifying-shocks-time-varying-volatility/Lewis.md',
      'Review of Economic Studies 88(6), 2021',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.bertsche-braun': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.bertsche-braun',
    'literatureSections.1.body',
    'Bertsche and Braun (2022, Abstract and Section 2) use independent latent AR(1) log-variance processes for structural shocks.',
    primaryEvidence(
      'bertsche-braun-2022',
      'Abstract and Section 2',
      'Each structural shock is conditionally Gaussian with its own latent log variance, and the log variances follow mutually independent stationary AR(1) processes.',
      'raw/bertsche-2022-svar-stochastic-volatility/Bertsche Braun.md',
      'Journal of Business & Economic Statistics 40(2), 2022',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.bertsche-braun-estimation': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.bertsche-braun-estimation',
    'literatureSections.1.body',
    'They develop full and partial identification with maximum-likelihood EM algorithms.',
    primaryEvidence(
      'bertsche-braun-2022',
      'Abstract; Sections 2-3',
      'The paper derives full and partial identification conditions from stochastic volatility and supplies maximum-likelihood expectation-maximization procedures for estimation under both cases.',
      'raw/bertsche-2022-svar-stochastic-volatility/Bertsche Braun.md',
      'Journal of Business & Economic Statistics 40(2), 2022',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.virolainen': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.virolainen',
    'literatureSections.1.body',
    'Virolainen (2025, Abstract and Sections 1 and 3) lets volatility-regime probabilities depend on lagged observations.',
    primaryEvidence(
      'virolainen-2025',
      'Abstract; Sections 1 and 3',
      'The model specifies endogenous mixing weights for volatility regimes as functions of lagged observables, rather than imposing exogenous Markov transition probabilities or fixed break dates.',
      'raw/virolainen-2025-endogenous-switching-volatility-svar/A Statistically Identified Structural Vector Autoregression with Endogenously Switching Volatility Regime.md',
      'Published article version captured in the vault (2025)',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.variants.virolainen-partial': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.variants.virolainen-partial',
    'literatureSections.1.body',
    'She derives sign-and-zero conditions for identifying selected shocks when full statistical identification fails.',
    primaryEvidence(
      'virolainen-2025',
      'Section 3',
      'When the volatility process does not statistically identify every column, the paper derives conditions under which sign and zero restrictions can still identify selected structural shocks.',
      'raw/virolainen-2025-endogenous-switching-volatility-svar/A Statistically Identified Structural Vector Autoregression with Endogenously Switching Volatility Regime.md',
      'Published article version captured in the vault (2025)',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.applications.rigobon-sack': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.applications.rigobon-sack',
    'literatureSections.2.body',
    'Rigobon and Sack (2003; working-paper Abstract) use stock-return heteroskedasticity to identify the Federal Reserve\'s reaction to stock-market movements despite the simultaneous response of stock prices to interest rates.',
    primaryEvidence(
      'rigobon-sack-2003',
      'Working-paper Abstract',
      'The paper exploits shifts in stock-market volatility to identify the monetary-policy reaction to stock returns while allowing stock prices and interest rates to respond to one another contemporaneously.',
      'raw/rigobon-2001-monetary-policy-stock-market/Rigobon Sack 2001 - Measuring the reaction of monetary policy to the stock market.md',
      'NBER Working Paper 8350 (2001), underlying Quarterly Journal of Economics 118(2), 2003',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.applications.normandin-method': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.applications.normandin-method',
    'literatureSections.2.body',
    'Normandin and Phaneuf (2004, Abstract and Section 5) use conditional heteroskedasticity to test monetary-policy targeting and contemporaneous orthogonality restrictions.',
    primaryEvidence(
      'normandin-phaneuf-2004',
      'Abstract and Section 5',
      'Their heteroskedastic SVAR estimates alternative monetary-policy equations and uses overidentifying tests to assess policy-target and contemporaneous orthogonality restrictions.',
      'raw/normandin-2004-monetary-policy-heteroskedasticity/1-s2.0-S0304393204000698-main.md',
      'Journal of Monetary Economics 51(8), 2004',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.applications.normandin-targets': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.applications.normandin-targets',
    'literatureSections.2.body',
    'They reject both interest-rate and non-borrowed-reserve targeting in their post-1982 U.S. sample.',
    primaryEvidence(
      'normandin-phaneuf-2004',
      'Section 5',
      'The empirical specification tests reject both the federal-funds-rate targeting model and the nonborrowed-reserves targeting model for the post-1982 sample.',
      'raw/normandin-2004-monetary-policy-heteroskedasticity/1-s2.0-S0304393204000698-main.md',
      'Journal of Monetary Economics 51(8), 2004',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.applications.normandin-orthogonality': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.applications.normandin-orthogonality',
    'literatureSections.2.body',
    'They also reject the restrictions that make policy shocks contemporaneously orthogonal to macroeconomic variables.',
    primaryEvidence(
      'normandin-phaneuf-2004',
      'Abstract and Section 5',
      'The reported tests reject the maintained restrictions that monetary-policy innovations are contemporaneously orthogonal to the model\'s macroeconomic variables.',
      'raw/normandin-2004-monetary-policy-heteroskedasticity/1-s2.0-S0304393204000698-main.md',
      'Journal of Monetary Economics 51(8), 2004',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.applications.lewis': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.applications.lewis',
    'literatureSections.2.body',
    'Lewis (2021, Abstract and Section 4) applies his method to U.S. fiscal shocks and reports peak multipliers of 0.86 for tax cuts and 0.75 for government spending.',
    primaryEvidence(
      'lewis-2021',
      'Abstract and Section 4',
      'The fiscal application reports peak multipliers of 0.86 for a tax cut and 0.75 for government spending using the volatility-based identification procedure.',
      'raw/lewis-2021-identifying-shocks-time-varying-volatility/Lewis.md',
      'Review of Economic Studies 88(6), 2021',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.applications.bertsche-braun': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.applications.bertsche-braun',
    'literatureSections.2.body',
    'Bertsche and Braun (2022, Abstract and Section 5) use instrumental-variable restrictions as overidentifying tests after stochastic-volatility identification in an oil-market application.',
    primaryEvidence(
      'bertsche-braun-2022',
      'Abstract and Section 5',
      'In the oil application, stochastic volatility identifies the model before external-instrument restrictions are imposed, allowing the latter to be evaluated as overidentifying restrictions.',
      'raw/bertsche-2022-svar-stochastic-volatility/Bertsche Braun.md',
      'Journal of Business & Economic Statistics 40(2), 2022',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.limits.mopmq-separation': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.limits.mopmq-separation',
    'literatureSections.3.body',
    'Montiel Olea, Plagborg-M&oslash;ller, and Qian (2022, Section IV) show that conditional shock orthogonality identifies the impact directions only when relative shock variances change by distinct amounts.',
    primaryEvidence(
      'montiel-olea-plagborg-moller-qian-2022',
      'Section IV',
      'Their conditional-heteroskedasticity argument identifies the structural columns when the shocks remain conditionally orthogonal and their conditional variances exhibit distinct relative movements.',
      'raw/montielolea-2022-svar-higher-moments/montiel-olea-et-al-2022-svar-identification-from-higher-moments-has-the-simultaneous-causality-problem-been-solved.md',
      'Review of Economic Studies 89(1), 2022',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.limits.mopmq-weak': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.limits.mopmq-weak',
    'literatureSections.3.body',
    'Their Section V warns that higher-moment identification can be weak when the additional moments are estimated imprecisely in moderate samples.',
    primaryEvidence(
      'montiel-olea-plagborg-moller-qian-2022',
      'Section V',
      'The paper emphasizes that sampling uncertainty in higher-order or conditional moment estimates can translate into weak structural identification in empirically realistic sample sizes.',
      'raw/montielolea-2022-svar-higher-moments/montiel-olea-et-al-2022-svar-identification-from-higher-moments-has-the-simultaneous-causality-problem-been-solved.md',
      'Review of Economic Studies 89(1), 2022',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.limits.kpm-causal': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.limits.kpm-causal',
    'literatureSections.3.body',
    'Koles&aacute;r and Plagborg-M&oslash;ller (2025, Abstract and Sections 1 and 4) show that heteroskedasticity-based estimands can be nonzero with no causal effect or have the wrong sign under nonlinear data generation.',
    primaryEvidence(
      'kolesar-plagborg-moller-2025',
      'Abstract; Sections 1 and 4',
      'The paper constructs nonlinear data-generating processes in which heteroskedasticity-based linear estimands are nonzero despite zero causal effects or have signs opposite to the relevant causal effects.',
      'raw/kolesar-2025-dynamic-causal-effects-nonlinear/temp_nonlinear.md',
      'Published article version captured in the vault (2025)',
    ),
    '2026-07-19',
  ),
  'heteroskedasticity.limits.kpm-sets': pageClaim(
    'heteroskedasticity',
    'heteroskedasticity.limits.kpm-sets',
    'literatureSections.3.body',
    'Their natural nonparametric extension of heteroskedastic identification yields wide identified sets.',
    primaryEvidence(
      'kolesar-plagborg-moller-2025',
      'Sections 1 and 4',
      'Their nonparametric extension of identification through heteroskedasticity generally leaves a broad set of admissible causal effects rather than a tight point-identified quantity.',
      'raw/kolesar-2025-dynamic-causal-effects-nonlinear/temp_nonlinear.md',
      'Published article version captured in the vault (2025)',
    ),
    '2026-07-19',
  ),
  'independent.origins.comon': independentClaim(
    'independent.origins.comon',
    'literatureSections.0.body',
    'Comon (1994, Theorem 11 and Corollary 13) shows that, in the linear ICA model, mutually independent non-deterministic components with at most one Gaussian component are recovered only up to scale and permutation.',
    primaryEvidence(
      'comon-1994',
      'Theorem 11 and Corollary 13, pp. 294–295',
      'The theorem restricts independence-preserving orthogonal transformations to scaled permutations when at most one non-deterministic component is Gaussian; the corollary extends the result to full-rank linear mixtures.',
      'https://core.ac.uk/download/pdf/52776748.pdf',
      'Published Signal Processing article (1994)',
    ),
  ),
  'independent.origins.chen-bickel': independentClaim(
    'independent.origins.chen-bickel',
    'literatureSections.0.body',
    'Chen and Bickel (2006) construct a semiparametrically efficient ICA estimator using estimated density scores.',
    primaryEvidence(
      'chen-bickel-2006',
      'Abstract; Sections 2.3–2.4',
      'The paper derives the semiparametric efficient score and estimates the unknown marginal density score functions with B-splines before constructing the estimator.',
      'raw/chen-2006-efficient-ica/EFFICIENT_INDEPENDENT_COMPONENT_ANALYSIS.md',
      'Published Annals of Statistics article (2006)',
    ),
  ),
  'independent.origins.bonhomme-robin': independentClaim(
    'independent.origins.bonhomme-robin',
    'literatureSections.0.body',
    'Bonhomme and Robin (2009) show that second-to-fourth moments can identify factor loadings in a noisy linear factor model.',
    primaryEvidence(
      'bonhomme-robin-2009',
      'Abstract; Theorem 4',
      'The paper identifies the factor-loading matrix in a noisy linear factor model from covariance, coskewness, and excess-cokurtosis restrictions under the stated rank and non-Gaussianity conditions.',
      'raw/bonhomme-2009-noisy-ica/Consistent_noisy_independent_component_analysis.md',
      'Published Journal of Econometrics article (2009)',
    ),
  ),
  'independent.origins.lms': independentClaim(
    'independent.origins.lms',
    'literatureSections.0.body',
    'Lanne, Meitz, and Saikkonen (2017) carry independent non-Gaussian identification into a dynamic SVAR and derive maximum-likelihood estimation, conventional inference, and tests of economic restrictions.',
    primaryEvidence(
      'lanne-meitz-saikkonen-2017',
      'Abstract; Theorem 1; Sections 4.4–4.6',
      'The paper establishes SVAR identification under independent non-Gaussian errors, develops joint maximum-likelihood and three-step estimators with conventional asymptotics, and shows how short- and long-run restrictions can be tested.',
      'raw/lanne-2017-non-gaussian-svar/Identification_and_estimation_of_non-Gaussian_structural_vector.md',
      'Published Journal of Econometrics article (2017)',
    ),
  ),
  'independent.origins.gmr': independentClaim(
    'independent.origins.gmr',
    'literatureSections.0.body',
    'Gouriéroux, Monfort, and Renne (2017) establish consistency and asymptotic inference for orthogonally constrained multi-unit pseudo-maximum likelihood under conditions on the chosen pseudo-densities.',
    primaryEvidence(
      'gourieroux-monfort-renne-2017',
      'Abstract; Sections 2.1–2.5',
      'The paper formulates PML over an orthogonal mixing matrix, states the distributional and pseudo-density identification assumptions needed for consistency, and derives asymptotic inference and tests.',
      'raw/gourieroux-2017-ica-svar/Statistical_inference_for_independent_component_analysis_Application.md',
      'Published Journal of Econometrics article (2017)',
    ),
  ),
  'independent.estimation.lewis': independentClaim(
    'independent.estimation.lewis',
    'literatureSections.1.body',
    'Lewis (2025) surveys likelihood, pseudo-likelihood, semiparametric, algorithmic, and moment-based routes that use different amounts of distributional information.',
    primaryEvidence(
      'lewis-2025-higher-moments',
      'Abstract; Sections 4.1–4.3',
      'The review separates the main non-Gaussian identification result from parametric ML, PML, ICA algorithms, semiparametric methods, and finite-moment GMM implementations.',
      'raw/lewis-2025-identification-higher-moments-macroeconometrics/Identification Based on Higher Moments in Macroeconometrics.md',
      'Published Annual Review of Economics article (2025)',
    ),
  ),
  'independent.estimation.guay': independentClaim(
    'independent.estimation.guay',
    'literatureSections.1.body',
    'Guay (2020) uses ranks of reduced-form coskewness and excess-cokurtosis matrices to diagnose whether the whole system or only a subsystem is identified.',
    primaryEvidence(
      'guay-2020',
      'Abstract; Sections 3.2.1 and 4',
      'The ranks of reduced-form third- and fourth-moment matrices determine the number of skewed and non-mesokurtic shocks and therefore the dimension of the identified subsystem; bootstrap rank tests implement the diagnostic.',
      'raw/guay-2020-higher-unconditional-moments-svar/1-s2.0-S0304407620303651-main.md',
      'Published Journal of Econometrics article',
    ),
  ),
  'independent.estimation.keweloh': independentClaim(
    'independent.estimation.keweloh',
    'literatureSections.1.body',
    'Keweloh (2021) constructs SVAR-GMM from covariance, coskewness, and cokurtosis restrictions under independent non-Gaussian shocks.',
    primaryEvidence(
      'keweloh-2021-gmm',
      'Propositions 1 and 3; Section 5',
      'The paper stacks variance, covariance, coskewness, and cokurtosis restrictions implied by independent non-Gaussian shocks and proves global identification before defining the SVAR-GMM estimator.',
      'raw/keweloh-2020-higher-moment-gmm-svar/A Generalized Method of Moments Estimator for Structural Vector Autoregressions Based on Higher Moments(3).md',
      'Published Journal of Economic Dynamics and Control article (2021)',
    ),
  ),
  'independent.estimation.hafner': independentClaim(
    'independent.estimation.hafner',
    'literatureSections.1.body',
    'Hafner, Herwartz, and Wang (2025) estimate shock densities with kernels and extend their likelihood framework to partial independence when only some shocks are credible independent components.',
    primaryEvidence(
      'hafner-herwartz-wang-2025',
      'Abstract; Sections 2.3 and 2.5',
      'The paper defines a kernel-density maximum-likelihood estimator for structural components and then develops a partial-independence version that identifies selected independent shocks while allowing dependence among the remainder.',
      'raw/hafner-2025-kernel-maximum-likelihood-independent-shocks/Statistical Identification of Independent Shocks with Kernel-based Maximum Likelihood Estimation and an Application to the Global Crude Oil Market.md',
      'Published Journal of Business & Economic Statistics article (2025)',
    ),
  ),
  'independent.combination.drautzburg-wright': independentClaim(
    'independent.combination.drautzburg-wright',
    'literatureSections.2.body',
    'Drautzburg and Wright (2023) invert higher-moment and nonparametric independence tests to refine a sign-restricted set; in Gaussian or weak-signal cases the refinement has little bite instead of forcing a point estimate.',
    primaryEvidence(
      'drautzburg-wright-2023',
      'Abstract; Sections 1 and 2.2.4',
      'The proposed identified set intersects sign restrictions with inverted dependence or independence tests; the paper explicitly shows that Gaussian or weak non-Gaussian information leaves the original sign-restricted set largely unchanged.',
      'raw/drautzburg-2023-refining-set-identification/Refining_set-identification_in_VARs_through_independence.md',
      'Published Journal of Applied Econometrics article (2023)',
    ),
  ),
  'independent.combination.keweloh-wang': independentClaim(
    'independent.combination.keweloh-wang',
    'literatureSections.2.body',
    'Keweloh and Wang (2025) use adaptive ridge shrinkage toward possibly invalid short-run restrictions, so valid restrictions can improve efficiency while invalid restrictions lose asymptotic influence; their skewness result needs mean independence rather than full independence.',
    primaryEvidence(
      'keweloh-wang-2025',
      'Abstract; Proposition 1; Sections 2.1–2.2',
      'The adaptive penalty retains efficiency gains from valid restrictions while its effect vanishes for invalid restrictions; Proposition 1 identifies skewed shocks under mutual mean independence, including common-volatility settings.',
      'raw/keweloh-2025-uncertain-short-run-restrictions/Uncertain Short-Run Restrictions and Statistically.md',
      '2025 paper version captured in the vault',
    ),
  ),
  'independent.application.lms': independentClaim(
    'independent.application.lms',
    'literatureSections.2.body',
    'Lanne, Meitz, and Saikkonen (2017) apply their model to U.S. monetary-policy and stock-market interactions and reject a recursive impact structure.',
    primaryEvidence(
      'lanne-meitz-saikkonen-2017',
      'Sections 5.2 and 6',
      'The U.S. application labels a contractionary monetary-policy shock, finds an immediate negative financial-market response, and reports Wald and likelihood-ratio evidence against the recursive impact restrictions.',
      'raw/lanne-2017-non-gaussian-svar/Identification_and_estimation_of_non-Gaussian_structural_vector.md',
      'Published Journal of Econometrics article (2017)',
    ),
  ),
  'independent.application.guay': independentClaim(
    'independent.application.guay',
    'literatureSections.2.body',
    'Guay (2020) finds the U.S. tax-shock subsystem identified while the spending-shock subsystem remains underidentified.',
    primaryEvidence(
      'guay-2020',
      'Sections 5 and 6',
      'The fiscal application identifies the subsystem linking reduced-form innovations to the tax shock but reports that the subsystem containing spending and non-fiscal shocks remains underidentified without another restriction.',
      'raw/guay-2020-higher-unconditional-moments-svar/1-s2.0-S0304407620303651-main.md',
      'Published Journal of Econometrics article',
    ),
  ),
  'independent.application.braun': independentClaim(
    'independent.application.braun',
    'literatureSections.2.body',
    'Braun (2023) estimates a Bayesian semiparametric oil-market SVAR with Dirichlet-process mixtures for the marginal shock distributions.',
    primaryEvidence(
      'braun-2023-nongaussianity',
      'Abstract; Sections 2 and 4',
      'The model combines weak economic priors with independent non-Gaussian shocks whose marginal distributions are assigned Dirichlet-process mixture models, then applies the framework to oil supply and demand.',
      'raw/braun-2023-oil-supply-demand-nongaussianity/Braun.md',
      'Published Journal of Applied Econometrics article (2023)',
    ),
  ),
  'independent.application.jarocinski': independentClaim(
    'independent.application.jarocinski',
    'literatureSections.2.body',
    'Jarociński (2024) separates four shocks from financial-market reactions to FOMC announcements using an independent fat-tailed Student-t specification.',
    primaryEvidence(
      'jarocinski-2024',
      'Abstract; Sections 2 and 4.1',
      'The paper estimates four independent Student-t shocks from high-frequency interest-rate and stock-price reactions to FOMC announcements and labels standard policy, Odyssean guidance, asset-purchase, and Delphic guidance shocks.',
      'raw/jarocinski-2024-unconventional-policy-shocks/1-s2.0-S0304393224000011-main.md',
      'Published Journal of Monetary Economics article (2024)',
    ),
  ),
  'independent.limits.common-volatility': independentClaim(
    'independent.limits.common-volatility',
    'literatureSections.3.body',
    'Montiel Olea, Plagborg-Møller, and Qian (2022) show that common stochastic volatility can leave shocks uncorrelated but dependent, so a linear ICA procedure may fail to recover a structurally interpretable object.',
    primaryEvidence(
      'montiel-olea-plagborg-moller-qian-2022',
      'Section II, pp. 482–483',
      'Their common-scale example produces orthogonal white-noise shocks that share volatility and are therefore dependent; because the ICA independence assumption fails, the resulting component need not have a structural interpretation.',
      'raw/montielolea-2022-svar-higher-moments/montiel-olea-et-al-2022-svar-identification-from-higher-moments-has-the-simultaneous-causality-problem-been-solved.md',
      'Published Review of Economic Studies article (2022)',
    ),
  ),
  'independent.limits.mesters-zwiernik': independentClaim(
    'independent.limits.mesters-zwiernik',
    'literatureSections.3.body',
    'Mesters and Zwiernik (2024) show that selected higher-order tensor restrictions can identify linear mixtures up to signed permutation in common-variance and other non-independent component models, but this requires a dependence pattern matched to those restrictions.',
    primaryEvidence(
      'mesters-2024-non-independent',
      'Theorem 5.5; Corollary 5.7; Sections 2.1 and 5.2',
      'Diagonal third-order or reflectionally invariant even-order tensor restrictions identify the mixing matrix up to signed permutation under model-specific genericity conditions, including common-variance and mean-independent component cases.',
      'raw/mesters-2024-non-independent-component-analysis/24-AOS2373.md',
      'Published Annals of Statistics article (2024)',
    ),
  ),
  'independent.limits.weak-and-labels': independentClaim(
    'independent.limits.weak-and-labels',
    'literatureSections.3.body',
    'Lewis (2025) emphasizes that small departures from Gaussianity can yield weak identification in realistic samples and that statistical information alone leaves shock labels unresolved.',
    primaryEvidence(
      'lewis-2025-higher-moments',
      'Sections 1, 5, and 6.4',
      'The review explains that near-Gaussian higher moments can be weak in finite samples and treats sign and column permutation as a separate economic labeling problem not solved by statistical orientation alone.',
      'raw/lewis-2025-identification-higher-moments-macroeconometrics/Identification Based on Higher Moments in Macroeconometrics.md',
      'Published Annual Review of Economics article (2025)',
    ),
  ),
  'independent.limits.nonlinearity': independentClaim(
    'independent.limits.nonlinearity',
    'literatureSections.3.body',
    'Kolesár and Plagborg-Møller (2025) show that latent-shock identification through non-Gaussianity is highly sensitive to departures from linearity and generally lacks a meaningful causal summary in an unrestricted nonlinear model.',
    primaryEvidence(
      'kolesar-plagborg-moller-2025',
      'Abstract; Sections 1 and 5',
      'The paper shows that even slight nonlinearities can make linear ICA procedures severely biased and that the nonparametric analogue of independent non-Gaussian latent shocks leaves an extremely large identified set.',
      'raw/kolesar-2025-dynamic-causal-effects-nonlinear/temp_nonlinear.md',
      'Published article version captured in the vault',
    ),
  ),
};

export default atlasClaims;
