const verifiedAt = '2026-07-16';

const pageUse = (order, annotation) => ({ order, listed: true, annotation });

const source = ({ uses, metadataStatus = 'verified-vault', ...entry }) => ({
  type: 'article',
  metadataStatus,
  verifiedAt,
  ...entry,
  url: entry.url ?? `https://doi.org/${entry.doi}`,
  pageUses: uses,
});

export const methodSources = {
  'sims-1980': source({
    id: 'sims-1980',
    citationKey: 'sims1980MacroeconomicsReality',
    bibtexPath: 'vault/citations/bibtex/sims-1980-macroeconomics-reality-497e8778.bib',
    authors: ['Christopher A. Sims'],
    year: 1980,
    title: 'Macroeconomics and Reality',
    venue: 'Econometrica',
    volume: '48',
    issue: '1',
    pages: '1–48',
    doi: '10.2307/1912017',
    uses: {
      overview: pageUse(1, 'the reduced-form VAR foundation and the boundary between orthogonalization and economic identification.'),
      recursive: pageUse(1, 'the VAR foundation and an early warning that recursive orthogonalization is not uniquely structural.'),
    },
  }),
  'christiano-eichenbaum-evans-2005': source({
    id: 'christiano-eichenbaum-evans-2005',
    citationKey: 'christianoEichenbaumEvans2005NominalRigidities',
    bibtexPath: 'vault/citations/bibtex/christiano-eichenbaum-evans-2005-nominal-rigidities-88a61ed0.bib',
    authors: ['Lawrence J. Christiano', 'Martin Eichenbaum', 'Charles L. Evans'],
    year: 2005,
    title: 'Nominal Rigidities and the Dynamic Effects of a Shock to Monetary Policy',
    venue: 'Journal of Political Economy',
    volume: '113',
    issue: '1',
    pages: '1–45',
    doi: '10.1086/426038',
    uses: { recursive: pageUse(3, 'a major recursive monetary-policy application and VAR-to-DSGE bridge.') },
  }),
  'kilian-2009': source({
    id: 'kilian-2009',
    citationKey: 'kilian2009NotAllOilPriceShocks',
    bibtexPath: 'vault/citations/bibtex/kilian-2009-not-all-oil-price-shocks-alike-disentangling-demand-supply-shocks-crude-oil-market-91253064.bib',
    authors: ['Lutz Kilian'],
    year: 2009,
    title: 'Not All Oil Price Shocks Are Alike: Disentangling Demand and Supply Shocks in the Crude Oil Market',
    venue: 'American Economic Review',
    volume: '99',
    issue: '3',
    pages: '1053–1069',
    doi: '10.1257/aer.99.3.1053',
    uses: { recursive: pageUse(4, 'a canonical monthly recursive oil-market application built on delay restrictions.') },
  }),
  'blanchard-perotti-2002': source({
    id: 'blanchard-perotti-2002',
    citationKey: 'blanchardPerotti2002EmpiricalCharacterization',
    bibtexPath: 'vault/citations/bibtex/blanchard-perotti-2002-empirical-characterization-4603cde6.bib',
    authors: ['Olivier Blanchard', 'Roberto Perotti'],
    year: 2002,
    title: 'An Empirical Characterization of the Dynamic Effects of Changes in Government Spending and Taxes on Output',
    venue: 'Quarterly Journal of Economics',
    volume: '117',
    issue: '4',
    pages: '1329–1368',
    doi: '10.1162/003355302320935043',
    uses: { recursive: pageUse(5, 'institutional timing and calibrated elasticities as a nonrecursive short-run alternative.') },
  }),
  'pesaran-shin-1998': source({
    id: 'pesaran-shin-1998',
    citationKey: 'pesaran1998GeneralizedImpulseResponseAnalysis',
    bibtexPath: 'vault/citations/bibtex/pesaran-1998-generalized-impulse-response-analysis-linear-multivariate-models-9373e0a9.bib',
    authors: ['M. Hashem Pesaran', 'Yongcheol Shin'],
    year: 1998,
    title: 'Generalized Impulse Response Analysis in Linear Multivariate Models',
    venue: 'Economics Letters',
    volume: '58',
    issue: '1',
    pages: '17–29',
    doi: '10.1016/S0165-1765(97)00214-0',
    uses: { recursive: pageUse(6, 'an order-invariant reduced-form contrast that is not structural-shock identification.') },
  }),
  'keweloh-wang-2025': source({
    id: 'keweloh-wang-2025',
    citationKey: 'keweloh2025UncertainShortRunRestrictions',
    bibtexPath: 'vault/citations/bibtex/keweloh-2025-uncertain-short-run-restrictions-statistically-identified-structural-vector-351c1d2e.bib',
    authors: ['Sascha A. Keweloh', 'Shu Wang'],
    year: 2025,
    title: 'Uncertain Short-Run Restrictions and Statistically Identified Structural Vector Autoregressions',
    venue: 'Journal of Applied Econometrics',
    doi: '10.1002/jae.70012',
    uses: {
      recursive: pageUse(7, 'a soft-restriction extension in which non-Gaussian information can support or overturn suspected zeros.'),
      'independent-shocks': pageUse(13, 'a hybrid design that combines uncertain short-run zeros with higher-moment information.'),
    },
  }),
  'faust-1998': source({
    id: 'faust-1998',
    citationKey: 'faust1998RobustnessIdentifiedVARConclusions',
    authors: ['Jon Faust'],
    year: 1998,
    title: 'The Robustness of Identified VAR Conclusions about Money',
    venue: 'Carnegie-Rochester Conference Series on Public Policy',
    volume: '49',
    pages: '207–244',
    doi: '10.1016/S0167-2231(99)00009-3',
    metadataStatus: 'verified-primary',
    uses: { sign: pageUse(1, 'an early sign-restriction analysis of monetary-policy conclusions.') },
  }),
  'canova-de-nicolo-2002': source({
    id: 'canova-de-nicolo-2002',
    citationKey: 'canovaDeNicolo2002MonetaryDisturbances',
    authors: ['Fabio Canova', 'Gianni De Nicoló'],
    year: 2002,
    title: 'Monetary Disturbances Matter for Business Fluctuations in the G-7',
    venue: 'Journal of Monetary Economics',
    volume: '49',
    issue: '6',
    pages: '1131–1159',
    doi: '10.1016/S0304-3932(02)00145-9',
    metadataStatus: 'verified-primary',
    uses: { sign: pageUse(2, 'an early multivariate sign-restriction design for G-7 monetary disturbances.') },
  }),
  'uhlig-2005': source({
    id: 'uhlig-2005',
    citationKey: 'uhlig2005WhatEffectsMonetaryPolicy',
    bibtexPath: 'vault/citations/bibtex/uhlig-2005-what-effects-monetary-policy-output-results-agnostic-identification-c9481409.bib',
    authors: ['Harald Uhlig'],
    year: 2005,
    title: 'What Are the Effects of Monetary Policy on Output? Results from an Agnostic Identification Procedure',
    venue: 'Journal of Monetary Economics',
    volume: '52',
    issue: '2',
    pages: '381–419',
    doi: '10.1016/j.jmoneco.2004.10.011',
    uses: { sign: pageUse(3, 'the canonical agnostic monetary-policy sign-restriction application.') },
  }),
  'rubio-ramirez-waggoner-zha-2010': source({
    id: 'rubio-ramirez-waggoner-zha-2010',
    citationKey: 'rubioRamirezWaggonerZha2010StructuralVAR',
    bibtexPath: 'vault/citations/bibtex/rubio-ramirez-waggoner-zha-2010-svar-identification-8450472a.bib',
    authors: ['Juan F. Rubio-Ramírez', 'Daniel F. Waggoner', 'Tao Zha'],
    year: 2010,
    title: 'Structural Vector Autoregressions: Theory of Identification and Algorithms for Inference',
    venue: 'Review of Economic Studies',
    volume: '77',
    issue: '2',
    pages: '665–696',
    doi: '10.1111/j.1467-937X.2009.00578.x',
    uses: {
      overview: pageUse(2, 'the general orthogonal-rotation, rank-condition, and inference framework behind the Atlas geometry.'),
      sign: pageUse(4, 'rotation geometry, global rank conditions, and QR/Haar sampling algorithms.'),
    },
  }),
  'mountford-uhlig-2009': source({
    id: 'mountford-uhlig-2009',
    citationKey: 'mountfordUhlig2009EffectsFiscalPolicy',
    bibtexPath: 'vault/citations/bibtex/mountford-uhlig-2009-effects-fiscal-policy-shocks-3a03a6b3.bib',
    authors: ['Andrew Mountford', 'Harald Uhlig'],
    year: 2009,
    title: 'What Are the Effects of Fiscal Policy Shocks?',
    venue: 'Journal of Applied Econometrics',
    volume: '24',
    issue: '6',
    pages: '960–992',
    doi: '10.1002/jae.1079',
    uses: { sign: pageUse(5, 'a major fiscal application using multiple shocks and a sequential penalty selector.') },
  }),
  'kilian-murphy-2012': source({
    id: 'kilian-murphy-2012',
    citationKey: 'kilian2012WhyAgnosticSignRestrictions',
    bibtexPath: 'vault/citations/bibtex/kilian-2012-why-agnostic-sign-restrictions-not-enough-98aa1981.bib',
    authors: ['Lutz Kilian', 'Daniel P. Murphy'],
    year: 2012,
    title: 'Why Agnostic Sign Restrictions Are Not Enough: Understanding the Dynamics of Oil Market VAR Models',
    venue: 'Journal of the European Economic Association',
    volume: '10',
    issue: '5',
    pages: '1166–1188',
    doi: '10.1111/j.1542-4774.2012.01080.x',
    uses: { sign: pageUse(6, 'the key demonstration that impact signs may need elasticity and activity bounds.') },
  }),
  'arias-rubio-ramirez-waggoner-2018': source({
    id: 'arias-rubio-ramirez-waggoner-2018',
    citationKey: 'arias2018InferenceBasedStructuralVector',
    bibtexPath: 'vault/citations/bibtex/arias-2018-inference-based-structural-vector-autoregressions-identified-sign-zero-6ba3d417.bib',
    authors: ['Jonas E. Arias', 'Juan F. Rubio-Ramírez', 'Daniel F. Waggoner'],
    year: 2018,
    title: 'Inference Based on Structural Vector Autoregressions Identified With Sign and Zero Restrictions: Theory and Applications',
    venue: 'Econometrica',
    volume: '86',
    issue: '2',
    pages: '685–720',
    doi: '10.3982/ECTA14468',
    uses: {
      sign: pageUse(7, 'conditional rotation sampling and the critique of penalty-function representatives.'),
      narrative: pageUse(8, 'admissible-set inference and the distinction between a set and an optimized representative.'),
      'max-share': pageUse(5, 'the key warning that optimization over rotations is not the same object as set inference.'),
    },
  }),
  'antolin-diaz-rubio-ramirez-2018': source({
    id: 'antolin-diaz-rubio-ramirez-2018',
    citationKey: 'diaz2018NarrativeSignRestrictionsSvars',
    bibtexPath: 'vault/citations/bibtex/diaz-2018-narrative-sign-restrictions-svars-debaceed.bib',
    authors: ['Juan Antolín-Díaz', 'Juan F. Rubio-Ramírez'],
    year: 2018,
    title: 'Narrative Sign Restrictions for SVARs',
    venue: 'American Economic Review',
    volume: '108',
    issue: '10',
    pages: '2802–2829',
    doi: '10.1257/aer.20161852',
    uses: {
      sign: pageUse(8, 'the formal dated shock-sign and historical-decomposition extension.'),
      narrative: pageUse(5, 'the formal shock-sign and historical-contribution framework with correct posterior weighting.'),
    },
  }),
  'romer-romer-1989': source({
    id: 'romer-romer-1989',
    citationKey: 'romerRomer1989DoesMonetaryPolicyMatter',
    authors: ['Christina D. Romer', 'David H. Romer'],
    year: 1989,
    title: 'Does Monetary Policy Matter? A New Test in the Spirit of Friedman and Schwartz',
    venue: 'NBER Macroeconomics Annual',
    volume: '4',
    pages: '121–184',
    doi: '10.1086/654103',
    metadataStatus: 'verified-primary',
    uses: { narrative: pageUse(1, 'a foundational historical-record construction of monetary-policy episodes.') },
  }),
  'romer-romer-2010': source({
    id: 'romer-romer-2010',
    citationKey: 'romerRomer2010MacroeconomicEffectsTaxChanges',
    authors: ['Christina D. Romer', 'David H. Romer'],
    year: 2010,
    title: 'The Macroeconomic Effects of Tax Changes: Estimates Based on a New Measure of Fiscal Shocks',
    venue: 'American Economic Review',
    volume: '100',
    issue: '3',
    pages: '763–801',
    doi: '10.1257/aer.100.3.763',
    metadataStatus: 'verified-primary',
    uses: { narrative: pageUse(2, 'a historical-record measure of legislated tax shocks and their timing.') },
  }),
  'ramey-2011': source({
    id: 'ramey-2011',
    citationKey: 'ramey2011IdentifyingGovernmentSpendingShocks',
    authors: ['Valerie A. Ramey'],
    year: 2011,
    title: "Identifying Government Spending Shocks: It's All in the Timing",
    venue: 'Quarterly Journal of Economics',
    volume: '126',
    issue: '1',
    pages: '1–50',
    doi: '10.1093/qje/qjq008',
    metadataStatus: 'verified-primary',
    uses: { narrative: pageUse(3, 'the canonical news-based treatment of government-spending timing.') },
  }),
  'kilian-2008-oil-supply': source({
    id: 'kilian-2008-oil-supply',
    citationKey: 'kilian2008ExogenousOilSupplyShocks',
    authors: ['Lutz Kilian'],
    year: 2008,
    title: 'Exogenous Oil Supply Shocks: How Big Are They and How Much Do They Matter for the U.S. Economy?',
    venue: 'Review of Economics and Statistics',
    volume: '90',
    issue: '2',
    pages: '216–240',
    doi: '10.1162/rest.90.2.216',
    metadataStatus: 'verified-primary',
    uses: { narrative: pageUse(4, 'a systematic historical construction and evaluation of exogenous oil-supply disruptions.') },
  }),
  'ludvigson-ma-ng-2021': source({
    id: 'ludvigson-ma-ng-2021',
    citationKey: 'ludvigson2021UncertaintyBusinessCycles',
    bibtexPath: 'vault/citations/bibtex/ludvigson-2021-uncertainty-business-cycles-exogenous-impulse-endogenous-response-d16dc7d2.bib',
    authors: ['Sydney C. Ludvigson', 'Sai Ma', 'Serena Ng'],
    year: 2021,
    title: 'Uncertainty and Business Cycles: Exogenous Impulse or Endogenous Response?',
    venue: 'American Economic Journal: Macroeconomics',
    volume: '13',
    issue: '4',
    pages: '369–410',
    doi: '10.1257/mac.20190171',
    uses: { narrative: pageUse(7, 'event inequalities and external-variable sign constraints for macro and financial uncertainty.') },
  }),
  'blanchard-quah-1989': source({
    id: 'blanchard-quah-1989',
    citationKey: 'blanchardQuah1989DynamicEffects',
    authors: ['Olivier J. Blanchard', 'Danny Quah'],
    year: 1989,
    title: 'The Dynamic Effects of Aggregate Demand and Supply Disturbances',
    venue: 'American Economic Review',
    volume: '79',
    issue: '4',
    pages: '655–673',
    doi: '10.2307/1827922',
    metadataStatus: 'verified-primary',
    uses: { 'long-run': pageUse(1, 'the benchmark permanent-supply versus transitory-demand long-run SVAR.') },
  }),
  'king-plosser-stock-watson-1991': source({
    id: 'king-plosser-stock-watson-1991',
    citationKey: 'kingPlosserStockWatson1991StochasticTrends',
    authors: ['Robert G. King', 'Charles I. Plosser', 'James H. Stock', 'Mark W. Watson'],
    year: 1991,
    title: 'Stochastic Trends and Economic Fluctuations',
    venue: 'American Economic Review',
    volume: '81',
    issue: '4',
    pages: '819–840',
    url: 'https://www.nber.org/papers/w2229',
    metadataStatus: 'verified-primary',
    versionNote: 'The public NBER record links the 1987 working paper to the 1991 American Economic Review version.',
    uses: { 'long-run': pageUse(2, 'common trends and the balanced-growth-shock application.') },
  }),
  'gali-1999': source({
    id: 'gali-1999',
    citationKey: 'gali1999TechnologyEmploymentBusinessCycle',
    authors: ['Jordi Galí'],
    year: 1999,
    title: 'Technology, Employment, and the Business Cycle: Do Technology Shocks Explain Aggregate Fluctuations?',
    venue: 'American Economic Review',
    volume: '89',
    issue: '1',
    pages: '249–271',
    doi: '10.1257/aer.89.1.249',
    metadataStatus: 'verified-primary',
    uses: { 'long-run': pageUse(3, 'the influential technology-shock application and the hours-response debate.') },
  }),
  'faust-leeper-1997': source({
    id: 'faust-leeper-1997',
    citationKey: 'faustLeeper1997LongRunRestrictions',
    authors: ['Jon Faust', 'Eric M. Leeper'],
    year: 1997,
    title: 'When Do Long-Run Identifying Restrictions Give Reliable Results?',
    venue: 'Journal of Business & Economic Statistics',
    volume: '15',
    issue: '3',
    pages: '345–353',
    doi: '10.1080/07350015.1997.10524712',
    metadataStatus: 'verified-primary',
    uses: { 'long-run': pageUse(4, 'the central omitted-shock, dynamic-aggregation, and time-aggregation critique.') },
  }),
  'beaudry-portier-2006': source({
    id: 'beaudry-portier-2006',
    citationKey: 'beaudryPortier2006StockPricesNews',
    authors: ['Paul Beaudry', 'Franck Portier'],
    year: 2006,
    title: 'Stock Prices, News, and Economic Fluctuations',
    venue: 'American Economic Review',
    volume: '96',
    issue: '4',
    pages: '1293–1307',
    doi: '10.1257/aer.96.4.1293',
    metadataStatus: 'verified-primary',
    uses: { 'long-run': pageUse(5, 'stock-price and productivity restrictions for news about future technology.') },
  }),
  'kurmann-mertens-2014': source({
    id: 'kurmann-mertens-2014',
    citationKey: 'kurmannMertens2014StockPricesNewsComment',
    authors: ['André Kurmann', 'Elmar Mertens'],
    year: 2014,
    title: 'Stock Prices, News, and Economic Fluctuations: Comment',
    venue: 'American Economic Review',
    volume: '104',
    issue: '4',
    pages: '1439–1445',
    doi: '10.1257/aer.104.4.1439',
    metadataStatus: 'verified-primary',
    uses: { 'long-run': pageUse(6, 'the nonuniqueness critique for news-shock restrictions in larger cointegrated systems.') },
  }),
  'uhlig-2004': source({
    id: 'uhlig-2004',
    citationKey: 'uhlig2004WhatMovesGNP',
    type: 'working-paper',
    authors: ['Harald Uhlig'],
    year: 2004,
    title: 'What Moves GNP?',
    venue: 'Econometric Society North American Winter Meetings',
    url: 'https://ideas.repec.org/p/ecm/nawm04/636.html',
    metadataStatus: 'verified-public-record',
    uses: { 'max-share': pageUse(1, 'an early formulation identifying a shock by the forecast-error variance it explains.') },
  }),
  'barsky-sims-2011': source({
    id: 'barsky-sims-2011',
    citationKey: 'barskySims2011NewsShocksBusinessCycles',
    authors: ['Robert B. Barsky', 'Eric R. Sims'],
    year: 2011,
    title: 'News Shocks and Business Cycles',
    venue: 'Journal of Monetary Economics',
    volume: '58',
    issue: '3',
    pages: '273–289',
    doi: '10.1016/j.jmoneco.2011.03.001',
    metadataStatus: 'verified-primary',
    uses: { 'max-share': pageUse(2, 'the influential zero-impact plus maximum-future-productivity-FEVD news-shock design.') },
  }),
  'caldara-et-al-2016': source({
    id: 'caldara-et-al-2016',
    citationKey: 'caldara2016MacroeconomicImpactFinancialUncertainty',
    bibtexPath: 'vault/citations/bibtex/caldara-2016-macroeconomic-impact-financial-uncertainty-shocks-25868ce8.bib',
    authors: ['Dario Caldara', 'Cristina Fuentes-Albero', 'Simon Gilchrist', 'Egon Zakrajšek'],
    year: 2016,
    title: 'The Macroeconomic Impact of Financial and Uncertainty Shocks',
    venue: 'European Economic Review',
    volume: '88',
    pages: '185–207',
    doi: '10.1016/j.euroecorev.2016.02.002',
    uses: { 'max-share': pageUse(3, 'a related sequential penalty selector for uncertainty and financial shocks.') },
  }),
  'carriero-volpicella-2025': source({
    id: 'carriero-volpicella-2025',
    citationKey: 'carriero2025MaxShareIdentificationMultiple',
    bibtexPath: 'vault/citations/bibtex/carriero-2025-max-share-identification-multiple-shocks-application-uncertainty-financial-186a6e6a.bib',
    authors: ['Andrea Carriero', 'Alessio Volpicella'],
    year: 2025,
    title: 'Max Share Identification of Multiple Shocks: An Application to Uncertainty and Financial Conditions',
    venue: 'Journal of Business & Economic Statistics',
    volume: '43',
    issue: '1',
    doi: '10.1080/07350015.2024.2316829',
    uses: { 'max-share': pageUse(4, 'joint multi-shock optimization with FEVD-dominance restrictions.') },
  }),
  'comon-1994': source({
    id: 'comon-1994',
    citationKey: 'comon1994IndependentComponentAnalysis',
    authors: ['Pierre Comon'],
    year: 1994,
    title: 'Independent Component Analysis, a New Concept?',
    venue: 'Signal Processing',
    volume: '36',
    issue: '3',
    pages: '287–314',
    doi: '10.1016/0165-1684(94)90029-9',
    metadataStatus: 'verified-primary',
    uses: { 'independent-shocks': pageUse(1, 'the foundational ICA formulation of uniqueness up to scale and permutation.') },
  }),
  'lewis-2025-higher-moments': source({
    id: 'lewis-2025-higher-moments',
    citationKey: 'lewis2025IdentificationBasedHigherMoments',
    bibtexPath: 'vault/citations/bibtex/lewis-2025-identification-based-higher-moments-macroeconometrics-77da8cb2.bib',
    authors: ['Daniel J. Lewis'],
    year: 2025,
    title: 'Identification Based on Higher Moments in Macroeconometrics',
    venue: 'Annual Review of Economics',
    volume: '17',
    pages: '665–693',
    doi: '10.1146/annurev-economics-070124-051419',
    uses: { 'independent-shocks': pageUse(2, 'a current review of higher-moment identification, diagnostics, and weak-signal concerns.') },
  }),
  'chen-bickel-2006': source({
    id: 'chen-bickel-2006',
    citationKey: 'paper1980EfficientIndependentComponentAnalysis',
    bibtexPath: 'vault/citations/bibtex/paper-1980-efficient-independent-component-analysis-e13a5918.bib',
    authors: ['Aiyou Chen', 'Peter J. Bickel'],
    year: 2006,
    title: 'Efficient Independent Component Analysis',
    venue: 'Annals of Statistics',
    volume: '34',
    issue: '6',
    pages: '2825–2855',
    doi: '10.1214/009053606000000955',
    uses: { 'independent-shocks': pageUse(3, 'efficient semiparametric ICA using estimated density scores.') },
  }),
  'bonhomme-robin-2009': source({
    id: 'bonhomme-robin-2009',
    citationKey: 'bonhomme2009ConsistentNoisyIndependentComponent',
    bibtexPath: 'vault/citations/bibtex/bonhomme-2009-consistent-noisy-independent-component-analysis-6833beff.bib',
    authors: ['Stéphane Bonhomme', 'Jean-Marc Robin'],
    year: 2009,
    title: 'Consistent Noisy Independent Component Analysis',
    venue: 'Journal of Econometrics',
    volume: '149',
    issue: '1',
    pages: '12–25',
    doi: '10.1016/j.jeconom.2008.12.019',
    uses: { 'independent-shocks': pageUse(4, 'cumulant-based recovery of independent factors in noisy measurement systems.') },
  }),
  'lanne-meitz-saikkonen-2017': source({
    id: 'lanne-meitz-saikkonen-2017',
    citationKey: 'lanne2016IdentificationEstimationNonGaussian',
    bibtexPath: 'vault/citations/bibtex/lanne-2016-identification-estimation-non-gaussian-structural-vector-autoregressions-6b3c5636.bib',
    authors: ['Markku Lanne', 'Mika Meitz', 'Pentti Saikkonen'],
    year: 2017,
    title: 'Identification and Estimation of Non-Gaussian Structural Vector Autoregressions',
    venue: 'Journal of Econometrics',
    volume: '196',
    issue: '2',
    pages: '288–304',
    doi: '10.1016/j.jeconom.2016.06.002',
    versionNote: 'The vault record uses the 2016 online-publication year; the Atlas uses the 2017 journal-volume year.',
    uses: { 'independent-shocks': pageUse(5, 'the likelihood-based translation of non-Gaussian ICA identification into dynamic SVARs.') },
  }),
  'gourieroux-monfort-renne-2017': source({
    id: 'gourieroux-monfort-renne-2017',
    citationKey: 'gourieroux2016StatisticalInferenceIndependentComponent',
    bibtexPath: 'vault/citations/bibtex/gourieroux-2016-statistical-inference-independent-component-analysis-application-structural-var-438a2c20.bib',
    authors: ['Christian Gouriéroux', 'Alain Monfort', 'Jean-Paul Renne'],
    year: 2017,
    title: 'Statistical Inference for Independent Component Analysis: Application to Structural VAR Models',
    venue: 'Journal of Econometrics',
    volume: '196',
    issue: '1',
    pages: '111–126',
    doi: '10.1016/j.jeconom.2016.05.009',
    versionNote: 'The vault record uses the 2016 online-publication year; the Atlas uses the 2017 journal-volume year.',
    uses: { 'independent-shocks': pageUse(6, 'pseudo-likelihood inference under deliberately misspecified shock densities.') },
  }),
  'guay-2020': source({
    id: 'guay-2020',
    citationKey: 'guay2020IdentificationStructuralVectorAutoregressions',
    bibtexPath: 'vault/citations/bibtex/guay-2020-identification-structural-vector-autoregressions-through-higher-unconditional-moments-620d4a1c.bib',
    authors: ['Alain Guay'],
    year: 2020,
    title: 'Identification of Structural Vector Autoregressions Through Higher Unconditional Moments',
    venue: 'Journal of Econometrics',
    volume: '225',
    issue: '1',
    pages: '27–46',
    doi: '10.1016/j.jeconom.2020.10.006',
    uses: { 'independent-shocks': pageUse(7, 'rank conditions using coskewness and excess-cokurtosis matrices.') },
  }),
  'keweloh-2021-gmm': source({
    id: 'keweloh-2021-gmm',
    citationKey: 'paper2020GeneralizedMethodMomentsEstimator',
    bibtexPath: 'vault/citations/bibtex/paper-2020-generalized-method-moments-estimator-structural-vector-autoregressions-based-55c13e37.bib',
    authors: ['Sascha Keweloh'],
    year: 2021,
    title: 'A Generalized Method of Moments Estimator for Structural Vector Autoregressions Based on Higher Moments',
    venue: 'Journal of Business & Economic Statistics',
    volume: '39',
    issue: '3',
    pages: '772–782',
    doi: '10.1080/07350015.2020.1730858',
    uses: { 'independent-shocks': pageUse(8, 'SVAR-GMM based on selected second-, third-, and fourth-moment restrictions.') },
  }),
  'montiel-olea-plagborg-moller-qian-2022': source({
    id: 'montiel-olea-plagborg-moller-qian-2022',
    citationKey: 'olea2022SvarIdentificationHigherMoments',
    bibtexPath: 'vault/citations/bibtex/olea-2022-svar-identification-higher-moments-simultaneous-causality-problem-been-21666567.bib',
    authors: ['José Luis Montiel Olea', 'Mikkel Plagborg-Møller', 'Eric Qian'],
    year: 2022,
    title: 'SVAR Identification from Higher Moments: Has the Simultaneous Causality Problem Been Solved?',
    venue: 'AEA Papers and Proceedings',
    volume: '112',
    pages: '481–485',
    doi: '10.1257/pandp.20221047',
    uses: {
      'independent-shocks': pageUse(9, 'a concise review of the maintained causal assumptions behind higher-moment identification.'),
      heteroskedasticity: pageUse(11, 'a critique of interpreting statistical higher-moment orientation as solved simultaneous causality.'),
    },
  }),
  'drautzburg-wright-2023': source({
    id: 'drautzburg-wright-2023',
    citationKey: 'drautzburg2023RefiningSetIdentificationVars',
    bibtexPath: 'vault/citations/bibtex/drautzburg-2023-refining-set-identification-vars-through-independence-2f06cfb0.bib',
    authors: ['Thorsten Drautzburg', 'Jonathan H. Wright'],
    year: 2023,
    title: 'Refining Set-Identification in VARs Through Independence',
    venue: 'Journal of Econometrics',
    volume: '235',
    issue: '2',
    pages: '1827–1847',
    doi: '10.1016/j.jeconom.2023.03.007',
    uses: { 'independent-shocks': pageUse(10, 'test inversion that refines, rather than forcibly point-identifies, a sign-restricted set.') },
  }),
  'braun-2023-nongaussianity': source({
    id: 'braun-2023-nongaussianity',
    citationKey: 'braun2023ImportanceSupplyDemandOil',
    bibtexPath: 'vault/citations/bibtex/braun-2023-importance-supply-demand-oil-prices-evidence-non-gaussianity-770e280a.bib',
    authors: ['Robin Braun'],
    year: 2023,
    title: 'The Importance of Supply and Demand for Oil Prices: Evidence from Non-Gaussianity',
    venue: 'Quantitative Economics',
    volume: '14',
    issue: '4',
    pages: '1163–1198',
    doi: '10.3982/QE2091',
    uses: { 'independent-shocks': pageUse(11, 'a Bayesian nonparametric oil-market application.') },
  }),
  'jarocinski-2024': source({
    id: 'jarocinski-2024',
    citationKey: 'jarocinski2024EstimatingFedSUnconventional',
    bibtexPath: 'vault/citations/bibtex/jarocinski-2024-estimating-fed-s-unconventional-policy-shocks-f3ee68f3.bib',
    authors: ['Marek Jarociński'],
    year: 2024,
    title: "Estimating the Fed's Unconventional Policy Shocks",
    venue: 'Journal of Monetary Economics',
    volume: '145',
    articleNumber: '103671',
    doi: '10.1016/j.jmoneco.2024.103671',
    uses: { 'independent-shocks': pageUse(12, 'an application separating four high-frequency FOMC shocks with non-Gaussian information.') },
  }),
  'kolesar-plagborg-moller-2025': source({
    id: 'kolesar-plagborg-moller-2025',
    citationKey: 'kolesar2025DynamicCausalEffectsNonlinear',
    bibtexPath: 'vault/citations/bibtex/kolesar-2025-dynamic-causal-effects-nonlinear-world-good-bad-ugly-5b5cfb30.bib',
    authors: ['Michal Kolesár', 'Mikkel Plagborg-Møller'],
    year: 2025,
    title: 'Dynamic Causal Effects in a Nonlinear World: The Good, the Bad, and the Ugly',
    venue: 'Journal of Business & Economic Statistics',
    volume: '43',
    issue: '4',
    pages: '737–754',
    doi: '10.1080/07350015.2025.2539478',
    metadataStatus: 'verified-primary',
    uses: {
      'independent-shocks': pageUse(14, 'the nonlinear causal-interpretation critique of latent-shock non-Gaussian identification.'),
      heteroskedasticity: pageUse(12, 'the nonlinear causal-interpretation critique of heteroskedasticity-based identification.'),
    },
  }),
  'sentana-fiorentini-2001': source({
    id: 'sentana-fiorentini-2001',
    citationKey: 'sentana2001IdentificationEstimationTestingConditionally',
    bibtexPath: 'vault/citations/bibtex/sentana-2001-identification-estimation-testing-conditionally-heteroskedastic-factor-models-e744c42c.bib',
    authors: ['Enrique Sentana', 'Gabriele Fiorentini'],
    year: 2001,
    title: 'Identification, Estimation and Testing of Conditionally Heteroskedastic Factor Models',
    venue: 'Journal of Econometrics',
    volume: '102',
    issue: '2',
    pages: '143–164',
    doi: '10.1016/S0304-4076(01)00051-3',
    uses: { heteroskedasticity: pageUse(1, 'the factor-model demonstration that distinct variance paths can remove rotational indeterminacy.') },
  }),
  'rigobon-2003': source({
    id: 'rigobon-2003',
    citationKey: 'rigobon2003IdentificationThroughHeteroskedasticity',
    bibtexPath: 'vault/citations/bibtex/rigobon-2003-identification-through-heteroskedasticity-e3ef9d5e.bib',
    authors: ['Roberto Rigobon'],
    year: 2003,
    title: 'Identification Through Heteroskedasticity',
    venue: 'Review of Economics and Statistics',
    volume: '85',
    issue: '4',
    pages: '777–792',
    doi: '10.1162/003465303772815727',
    uses: { heteroskedasticity: pageUse(2, 'the canonical covariance-regime treatment for simultaneous equations.') },
  }),
  'rigobon-sack-2003': source({
    id: 'rigobon-sack-2003',
    citationKey: 'rigobon2001MeasuringReactionMonetaryPolicy',
    bibtexPath: 'vault/citations/bibtex/rigobon-2001-measuring-reaction-monetary-policy-stock-market-02fefb1f.bib',
    authors: ['Roberto Rigobon', 'Brian Sack'],
    year: 2003,
    title: 'Measuring the Reaction of Monetary Policy to the Stock Market',
    venue: 'Quarterly Journal of Economics',
    volume: '118',
    issue: '2',
    pages: '639–669',
    doi: '10.1162/003355303321675490',
    versionNote: 'The Atlas uses the 2003 journal version rather than the 2001 NBER working-paper year.',
    uses: { heteroskedasticity: pageUse(3, 'the macro-finance application to monetary-policy and stock-market simultaneity.') },
  }),
  'normandin-phaneuf-2004': source({
    id: 'normandin-phaneuf-2004',
    citationKey: 'normandin2004MonetaryPolicyShocksTesting',
    bibtexPath: 'vault/citations/bibtex/normandin-2004-monetary-policy-shocks-testing-identification-conditions-under-time-2827ed6b.bib',
    authors: ['Michel Normandin', 'Louis Phaneuf'],
    year: 2004,
    title: 'Monetary Policy Shocks: Testing Identification Conditions Under Time-Varying Conditional Volatility',
    venue: 'Journal of Monetary Economics',
    volume: '51',
    issue: '6',
    pages: '1213–1237',
    doi: '10.1016/j.jmoneco.2004.04.002',
    uses: { heteroskedasticity: pageUse(4, 'a monetary SVAR that uses volatility information to test conventional restrictions.') },
  }),
  'lanne-lutkepohl-maciejowska-2010': source({
    id: 'lanne-lutkepohl-maciejowska-2010',
    citationKey: 'lanneLutkepohlMaciejowska2010StructuralVARMarkovSwitching',
    bibtexPath: 'vault/citations/bibtex/lanne-lutkepohl-maciejowska-2010-svar-markov-switching.bib',
    authors: ['Markku Lanne', 'Helmut Lütkepohl', 'Katarzyna Maciejowska'],
    year: 2010,
    title: 'Structural Vector Autoregressions with Markov Switching',
    venue: 'Journal of Economic Dynamics and Control',
    volume: '34',
    issue: '2',
    pages: '121–131',
    doi: '10.1016/j.jedc.2009.08.002',
    uses: { heteroskedasticity: pageUse(5, 'the Markov-switching covariance implementation of common structural axes.') },
  }),
  'milunovich-yang-2013': source({
    id: 'milunovich-yang-2013',
    citationKey: 'milunovich2010IdentifyingStructuralVarModels',
    bibtexPath: 'vault/citations/bibtex/milunovich-2010-identifying-structural-var-models-via-arch-effects-3796bd4f.bib',
    authors: ['Steven Milunovich', 'Mingyue Yang'],
    year: 2013,
    title: 'On Identifying Structural VAR Models via ARCH Effects',
    venue: 'Journal of Time Series Econometrics',
    volume: '5',
    issue: '2',
    pages: '117–131',
    doi: '10.1515/jtse-2013-0010',
    versionNote: 'The Atlas uses the 2013 journal year rather than the working-paper year in the old page copy.',
    uses: { heteroskedasticity: pageUse(6, 'joint identification of the impact matrix and structural ARCH/GARCH parameters.') },
  }),
  'lutkepohl-netsunajev-2017': source({
    id: 'lutkepohl-netsunajev-2017',
    citationKey: 'lutkepohlNetsunajev2017StructuralVectorAutoregressions',
    bibtexPath: 'vault/citations/bibtex/lutkepohl-netsunajev-2017-svar-smooth-transition-variances.bib',
    authors: ['Helmut Lütkepohl', 'Aleksei Netsunajev'],
    year: 2017,
    title: 'Structural Vector Autoregressions with Smooth Transition in Variances',
    venue: 'Journal of Economic Dynamics and Control',
    volume: '84',
    pages: '43–57',
    doi: '10.1016/j.jedc.2017.09.001',
    uses: { heteroskedasticity: pageUse(7, 'smooth-transition covariance states rather than a discrete break.') },
  }),
  'lewis-2021': source({
    id: 'lewis-2021',
    citationKey: 'lewis2021IdentifyingShocksTimeVaryingVolatility',
    bibtexPath: 'vault/citations/bibtex/lewis-2021-identifying-shocks-time-varying-volatility.bib',
    authors: ['Daniel J. Lewis'],
    year: 2021,
    title: 'Identifying Shocks via Time-Varying Volatility',
    venue: 'Review of Economic Studies',
    volume: '88',
    issue: '6',
    pages: '3086–3124',
    doi: '10.1093/restud/rdab009',
    uses: { heteroskedasticity: pageUse(8, 'rank diagnostics and identification from autocovariances of squared innovations.') },
  }),
  'bertsche-braun-2022': source({
    id: 'bertsche-braun-2022',
    citationKey: 'bertsche2022IdentificationStructuralVectorAutoregressions',
    bibtexPath: 'vault/citations/bibtex/bertsche-2022-identification-structural-vector-autoregressions-stochastic-volatility-bcffcf41.bib',
    authors: ['Dominik Bertsche', 'Robin Braun'],
    year: 2022,
    title: 'Identification of Structural Vector Autoregressions by Stochastic Volatility',
    venue: 'Journal of Business & Economic Statistics',
    volume: '40',
    issue: '1',
    pages: '328–341',
    doi: '10.1080/07350015.2020.1813588',
    uses: { heteroskedasticity: pageUse(9, 'identification using autocovariances of squared residuals generated by latent stochastic volatility.') },
  }),
  'virolainen-2025': source({
    id: 'virolainen-2025',
    citationKey: 'virolainen2025StatisticallyIdentifiedStructuralVector',
    bibtexPath: 'vault/citations/bibtex/virolainen-2025-statistically-identified-structural-vector-autoregression-endogenously-switching-volatility-c830ca84.bib',
    authors: ['Savi Virolainen'],
    year: 2025,
    title: 'A Statistically Identified Structural Vector Autoregression with Endogenously Switching Volatility Regime',
    venue: 'Journal of Business & Economic Statistics',
    doi: '10.1080/07350015.2024.2322090',
    uses: { heteroskedasticity: pageUse(10, 'endogenous regime probabilities and hybrid sign/zero completion under partial statistical identification.') },
  }),
};

export default methodSources;
