import { pageSections } from './page-sections.mjs';

const reviewedSection = (section) => ({
  page: 'proxy',
  citationStatus: 'verified',
  completenessStatus: 'complete-for-declared-scope',
  reviewedAt: '2026-07-16',
  reviewedHash: '',
  contentPaths: [],
  ...section,
});

export const atlasSections = {
  'proxy.hero.overview': reviewedSection({
    id: 'proxy.hero.overview',
    reviewedHash: '853984117e82ff40',
    title: 'Page overview',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored orientation with no paper-specific contribution claim.',
    contentPaths: ['cardIntro'],
    claimIds: ['proxy.validity.baseline'],
    coverageCategoryIds: ['identification', 'handbook'],
  }),
  'proxy.lab.overview': reviewedSection({
    id: 'proxy.lab.overview',
    reviewedHash: '4eb5814ffd0ba995',
    title: 'Interactive lab overview and maintained assumptions',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored explanation of the interactive simplification.',
    contentPaths: [
      'assumptionSummary',
      'atlasRuleSummary',
      'outputSummary',
      'intuitionAssumption',
      'intuitionTranslation',
      'intuition',
      'detail',
      'chartTakeaway',
    ],
    claimIds: [
      'proxy.validity.baseline',
      'proxy.estimation.atlas-criterion',
      'proxy.output.conditional-irfs',
    ],
    coverageCategoryIds: ['identification', 'estimator', 'handbook'],
  }),
  'proxy.lab.criterion': reviewedSection({
    id: 'proxy.lab.criterion',
    reviewedHash: 'fb4306b4cb83463f',
    title: 'Rotation criterion and diagnostic plots',
    renderMode: 'audit-only',
    displayReason: 'Atlas interaction and plot-reading instructions; research-estimator contrasts stay in the literature bridge.',
    contentPaths: [
      'criterionHeadline',
      'criterionIntro',
      'objective',
      'objectivePlotNote',
      'extraPlotNote',
      'plotTitle',
      'extra',
    ],
    claimIds: [
      'proxy.estimation.atlas-criterion',
      'proxy.diagnostics.scale-first-stage',
    ],
    coverageCategoryIds: ['identification', 'estimator', 'handbook'],
  }),
  'proxy.lab.irfs': reviewedSection({
    id: 'proxy.lab.irfs',
    reviewedHash: '6684b7e70c1752b5',
    title: 'Conditional impulse responses',
    renderMode: 'audit-only',
    displayReason: 'Atlas interaction instructions; advanced inference qualifications stay in the literature bridge.',
    contentPaths: ['irfIntro'],
    claimIds: ['proxy.output.conditional-irfs'],
    coverageCategoryIds: ['identification'],
  }),
  'proxy.reader.measurement': reviewedSection({
    id: 'proxy.reader.measurement',
    reviewedHash: 'be7b5ea1a74798d2',
    title: 'Reader step: instrument versus shock',
    renderMode: 'claim-text',
    contentPaths: ['readingSteps.0.title'],
    claimIds: ['proxy.measurement.instrument-not-shock'],
    coverageCategoryIds: ['foundational', 'identification'],
  }),
  'proxy.reader.relevance': reviewedSection({
    id: 'proxy.reader.relevance',
    reviewedHash: 'a2934fa4ab274723',
    title: 'Reader step: relevance versus exclusion',
    renderMode: 'claim-text',
    contentPaths: ['readingSteps.1.title'],
    claimIds: ['proxy.inference.weak-relevance-reading'],
    coverageCategoryIds: ['weakIdentification'],
  }),
  'proxy.reader.plots': reviewedSection({
    id: 'proxy.reader.plots',
    reviewedHash: '637c2c93e79cc092',
    title: 'Reader step: criterion plots and first-stage scale',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored plot-reading instructions with no paper-specific contribution claim.',
    contentPaths: ['readingSteps.2.title', 'readingSteps.2.body'],
    claimIds: ['proxy.diagnostics.scale-first-stage'],
    coverageCategoryIds: ['estimator', 'handbook'],
  }),
  'proxy.reader.output': reviewedSection({
    id: 'proxy.reader.output',
    reviewedHash: '2966544e263fc683',
    title: 'Reader step: conditional causal interpretation',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored interpretation guidance; advanced information-set conditions stay in the literature bridge.',
    contentPaths: ['readingSteps.3.title', 'readingSteps.3.body'],
    claimIds: ['proxy.output.conditional-irfs'],
    coverageCategoryIds: ['identification'],
  }),
  'proxy.literature.overview': reviewedSection({
    id: 'proxy.literature.overview',
    reviewedHash: '3ac4f5c8e739c0ea',
    title: 'Literature bridge overview',
    renderMode: 'audit-only',
    displayReason: 'Atlas synthesis that previews the directly cited literature subsections below.',
    contentPaths: ['literatureLead'],
    claimIds: [
      'proxy.history.external-instrument-origin',
      'proxy.inference.weak-and-invertibility',
      'proxy.inference.bayesian',
      'proxy.identification.multiple-proxies',
    ],
    coverageCategoryIds: [
      'foundational',
      'weakIdentification',
      'contaminationAndInvertibility',
      'bayesianAndSetInference',
      'multipleProxies',
    ],
  }),
  'proxy.literature.origins': reviewedSection({
    id: 'proxy.literature.origins',
    reviewedHash: 'acc180082bc51e02',
    title: 'Origins and baseline external-instrument idea',
    renderMode: 'claim-text',
    contentPaths: ['literatureSections.0.title'],
    claimIds: ['proxy.history.external-instrument-origin'],
    coverageCategoryIds: ['foundational', 'identification'],
  }),
  'proxy.literature.estimator': reviewedSection({
    id: 'proxy.literature.estimator',
    reviewedHash: '937aef9147cdd00b',
    title: 'Research estimator versus Atlas display',
    renderMode: 'claim-text',
    contentPaths: ['literatureSections.1.title'],
    claimIds: ['proxy.estimation.covariance-vector'],
    coverageCategoryIds: ['identification', 'estimator'],
  }),
  'proxy.literature.developments': reviewedSection({
    id: 'proxy.literature.developments',
    reviewedHash: 'c60b2e8a109ddf72',
    title: 'Methodological developments',
    renderMode: 'claim-text',
    contentPaths: ['literatureSections.2.title'],
    claimIds: [
      'proxy.inference.weak-and-invertibility',
      'proxy.inference.bootstrap',
      'proxy.inference.bayesian',
    ],
    coverageCategoryIds: [
      'weakIdentification',
      'contaminationAndInvertibility',
      'bootstrap',
      'bayesianAndSetInference',
    ],
  }),
  'proxy.literature.applications': reviewedSection({
    id: 'proxy.literature.applications',
    reviewedHash: 'b9da31b969b2304b',
    title: 'Applications and multiple-proxy variants',
    renderMode: 'claim-text',
    contentPaths: ['literatureSections.3.title'],
    claimIds: [
      'proxy.applications.fiscal-monetary',
      'proxy.applications.oil-carbon',
      'proxy.identification.multiple-proxies',
    ],
    coverageCategoryIds: ['representativeApplications', 'multipleProxies'],
  }),
  'proxy.literature.diagnostics': reviewedSection({
    id: 'proxy.literature.diagnostics',
    reviewedHash: '57895da446406d13',
    title: 'Critiques and applied diagnostics',
    renderMode: 'claim-text',
    contentPaths: ['literatureSections.4.title'],
    claimIds: ['proxy.diagnostics.failure-sequence'],
    coverageCategoryIds: [
      'weakIdentification',
      'contaminationAndInvertibility',
      'bootstrap',
      'multipleProxies',
    ],
  }),
  'proxy.questions.construction': reviewedSection({
    id: 'proxy.questions.construction',
    reviewedHash: '9d8fc1bcb9e77410',
    title: 'Application question: construction and timing',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored synthesis question; its evidence remains in the audit and cited literature discussion.',
    contentPaths: ['literatureQuestions.0'],
    claimIds: [
      'proxy.measurement.instrument-not-shock',
      'proxy.applications.fiscal-monetary',
      'proxy.applications.oil-carbon',
    ],
    coverageCategoryIds: ['foundational', 'representativeApplications'],
  }),
  'proxy.questions.strength': reviewedSection({
    id: 'proxy.questions.strength',
    reviewedHash: 'b2a1e338cd512965',
    title: 'Application question: first-stage strength',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored synthesis question; its evidence remains in the audit and cited literature discussion.',
    contentPaths: ['literatureQuestions.1'],
    claimIds: [
      'proxy.inference.weak-relevance-reading',
      'proxy.inference.bootstrap',
    ],
    coverageCategoryIds: ['weakIdentification', 'bootstrap'],
  }),
  'proxy.questions.exclusion': reviewedSection({
    id: 'proxy.questions.exclusion',
    reviewedHash: 'deaa36d812e81def',
    title: 'Application question: exclusion and information conditions',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored synthesis question; its evidence remains in the audit and cited literature discussion.',
    contentPaths: ['literatureQuestions.2'],
    claimIds: [
      'proxy.identification.partial-invertibility-reading',
      'proxy.diagnostics.failure-sequence',
    ],
    coverageCategoryIds: ['identification', 'contaminationAndInvertibility'],
  }),
  'proxy.questions.multiple': reviewedSection({
    id: 'proxy.questions.multiple',
    reviewedHash: 'b82159848e0f359a',
    title: 'Application question: several proxies and shocks',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored synthesis question; its evidence remains in the audit and cited literature discussion.',
    contentPaths: ['literatureQuestions.3'],
    claimIds: ['proxy.identification.multiple-proxies'],
    coverageCategoryIds: ['multipleProxies'],
  }),
  'proxy.questions.uncertainty': reviewedSection({
    id: 'proxy.questions.uncertainty',
    reviewedHash: 'aebb60044a54340b',
    title: 'Application question: uncertainty and inference',
    renderMode: 'audit-only',
    displayReason: 'Atlas-authored synthesis question; its evidence remains in the audit and cited literature discussion.',
    contentPaths: ['literatureQuestions.4'],
    claimIds: [
      'proxy.inference.weak-and-invertibility',
      'proxy.inference.bootstrap',
      'proxy.inference.bayesian',
    ],
    coverageCategoryIds: ['weakIdentification', 'bootstrap', 'bayesianAndSetInference'],
  }),
  ...pageSections,
};

export default atlasSections;

