import { methodSources } from './method-sources.mjs';

export const atlasSources = {
  'stock-watson-2012': {
    id: 'stock-watson-2012',
    citationKey: 'stockWatson2012DisentanglingChannels',
    type: 'article',
    authors: ['James H. Stock', 'Mark W. Watson'],
    year: 2012,
    title: 'Disentangling the Channels of the 2007-2009 Recession',
    venue: 'Brookings Papers on Economic Activity',
    issue: 'Spring',
    url: 'https://www.brookings.edu/articles/disentangling-the-channels-of-the-2007-2009-recession/',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 1,
        listed: true,
        annotation: 'an early published external-instrument implementation and a foundation for the modern SVAR-IV branch.',
      },
    },
  },
  'mertens-ravn-2013': {
    id: 'mertens-ravn-2013',
    citationKey: 'mertens2013DynamicEffectsPersonalCorporate',
    bibtexPath: 'vault/citations/bibtex/mertens-2013-dynamic-effects-personal-corporate-income-tax-changes-united-ca5e7610.bib',
    type: 'article',
    authors: ['Karel Mertens', 'Morten O. Ravn'],
    year: 2013,
    title: 'The Dynamic Effects of Personal and Corporate Income Tax Changes in the United States',
    venue: 'American Economic Review',
    volume: '103',
    issue: '4',
    pages: '1212–1247',
    doi: '10.1257/aer.103.4.1212',
    url: 'https://doi.org/10.1257/aer.103.4.1212',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 2,
        listed: true,
        annotation: 'the influential fiscal Proxy-SVAR application that treats narrative tax measures as noisy proxies for latent tax shocks.',
      },
    },
  },
  'kilian-lutkepohl-2017': {
    id: 'kilian-lutkepohl-2017',
    citationKey: 'kilianLutkepohl2017StructuralVectorAutoregressiveAnalysis',
    type: 'book',
    authors: ['Lutz Kilian', 'Helmut Lütkepohl'],
    year: 2017,
    title: 'Structural Vector Autoregressive Analysis',
    venue: 'Cambridge University Press',
    doi: '10.1017/9781108164818',
    url: 'https://doi.org/10.1017/9781108164818',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      overview: {
        order: 3,
        listed: true,
        annotation: 'the book-length map of SVAR identification, estimation, inference, and empirical practice behind the method pages.',
      },
      recursive: {
        order: 2,
        listed: true,
        annotation: 'Chapters 8?9 cover recursive, semistructural, and nonrecursive short-run identification.',
      },
      sign: {
        order: 10,
        listed: true,
        annotation: 'Chapter 13 provides the book-length treatment of signs, bounds, priors, algorithms, and reporting.',
      },
      narrative: {
        order: 6,
        listed: true,
        annotation: 'Chapters 7 and 13 connect historical shock measures, narrative restrictions, and set-valued inference.',
      },
      'long-run': {
        order: 7,
        listed: true,
        annotation: 'Chapters 10?12 cover stationary, integrated, cointegrated, and mixed long-run systems.',
      },
      'max-share': {
        order: 6,
        listed: true,
        annotation: 'Chapters 4 and 17 cover FEVD construction, nonfundamentalness, and technology-news selectors.',
      },
      proxy: {
        order: 3,
        listed: true,
        annotation: 'Chapter 15 gives the handbook treatment of identification from extraneous data, proxy strength, and weak-instrument inference.',
      },
    },
  },
  'gertler-karadi-2015': {
    id: 'gertler-karadi-2015',
    citationKey: 'gertler2015MonetaryPolicySurprises',
    bibtexPath: 'vault/citations/bibtex/gertler-2015-monetary-policy-surprises-credit-costs-economic-activity-990f9167.bib',
    type: 'article',
    authors: ['Mark Gertler', 'Peter Karadi'],
    year: 2015,
    title: 'Monetary Policy Surprises, Credit Costs, and Economic Activity',
    venue: 'American Economic Journal: Macroeconomics',
    volume: '7',
    issue: '1',
    pages: '44–76',
    doi: '10.1257/mac.20130329',
    url: 'https://doi.org/10.1257/mac.20130329',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 4,
        listed: true,
        annotation: 'the benchmark high-frequency monetary-policy application using announcement surprises as external instruments.',
      },
    },
  },
  'montiel-olea-stock-watson-2021': {
    id: 'montiel-olea-stock-watson-2021',
    citationKey: 'olea2021InferenceStructuralVectorAutoregressions',
    bibtexPath: 'vault/citations/bibtex/olea-2021-inference-structural-vector-autoregressions-identified-external-instrument-f1eb3461.bib',
    type: 'article',
    authors: ['José L. Montiel Olea', 'James H. Stock', 'Mark W. Watson'],
    year: 2021,
    title: 'Inference in Structural Vector Autoregressions Identified with an External Instrument',
    venue: 'Journal of Econometrics',
    volume: '225',
    issue: '1',
    pages: '74–87',
    doi: '10.1016/j.jeconom.2020.05.014',
    url: 'https://doi.org/10.1016/j.jeconom.2020.05.014',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 5,
        listed: true,
        annotation: 'the central weak-proxy reference, with Anderson–Rubin/Fieller-style confidence sets valid regardless of instrument strength.',
      },
    },
  },
  'miranda-agrippino-ricco-2023': {
    id: 'miranda-agrippino-ricco-2023',
    citationKey: 'agrippino2023IdentificationExternalInstrumentsStructural',
    bibtexPath: 'vault/citations/bibtex/agrippino-2023-identification-external-instruments-structural-vars-fd6fb3b4.bib',
    vaultDiscrepancy: 'Vault DOI is stale; Atlas metadata was rechecked against the Journal of Monetary Economics version of record.',
    type: 'article',
    authors: ['Silvia Miranda-Agrippino', 'Giovanni Ricco'],
    year: 2023,
    title: 'Identification with External Instruments in Structural VARs',
    venue: 'Journal of Monetary Economics',
    volume: '135',
    pages: '1–19',
    doi: '10.1016/j.jmoneco.2023.01.006',
    url: 'https://doi.org/10.1016/j.jmoneco.2023.01.006',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 6,
        listed: true,
        annotation: 'partial invertibility, limited lead–lag exogeneity, specification guidance, and tests for maintained information conditions.',
      },
    },
  },
  'jarocinski-karadi-2020': {
    id: 'jarocinski-karadi-2020',
    citationKey: 'jarocinski2020DeconstructingMonetaryPolicySurprises',
    bibtexPath: 'vault/citations/bibtex/jarocinski-2020-deconstructing-monetary-policy-surprises-role-information-shocks-4db61828.bib',
    type: 'article',
    authors: ['Marek Jarociński', 'Peter Karadi'],
    year: 2020,
    title: 'Deconstructing Monetary Policy Surprises: The Role of Information Shocks',
    venue: 'American Economic Journal: Macroeconomics',
    volume: '12',
    issue: '2',
    pages: '1–43',
    doi: '10.1257/mac.20180090',
    url: 'https://doi.org/10.1257/mac.20180090',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 7,
        listed: true,
        annotation: 'shows how announcement-window rate surprises can mix policy actions with central-bank information news.',
      },
    },
  },
  'jentsch-lunsford-2019': {
    id: 'jentsch-lunsford-2019',
    citationKey: 'jentsch2019DynamicEffectsPersonalCorporate',
    bibtexPath: 'vault/citations/bibtex/jentsch-2019-dynamic-effects-personal-corporate-income-tax-changes-united-4e6b9461.bib',
    type: 'article',
    authors: ['Carsten Jentsch', 'Kurt G. Lunsford'],
    year: 2019,
    title: 'The Dynamic Effects of Personal and Corporate Income Tax Changes in the United States: Comment',
    venue: 'American Economic Review',
    volume: '109',
    issue: '7',
    pages: '2655–2678',
    doi: '10.1257/aer.20162011',
    url: 'https://doi.org/10.1257/aer.20162011',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 8,
        listed: true,
        annotation: 'demonstrates the failure of the Rademacher wild bootstrap for Proxy-SVAR IRFs in the Mertens–Ravn design.',
      },
    },
  },
  'jentsch-lunsford-2022': {
    id: 'jentsch-lunsford-2022',
    citationKey: 'jentsch2022AsymptoticallyValidBootstrapInference',
    bibtexPath: 'vault/citations/bibtex/jentsch-2022-asymptotically-valid-bootstrap-inference-proxy-svars-e70a0167.bib',
    type: 'article',
    authors: ['Carsten Jentsch', 'Kurt G. Lunsford'],
    year: 2022,
    title: 'Asymptotically Valid Bootstrap Inference for Proxy SVARs',
    venue: 'Journal of Business & Economic Statistics',
    volume: '40',
    issue: '4',
    pages: '1876–1891',
    doi: '10.1080/07350015.2021.1990770',
    url: 'https://doi.org/10.1080/07350015.2021.1990770',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 9,
        listed: true,
        annotation: 'establishes residual-based moving-block bootstrap inference and its weak-proxy Anderson–Rubin extension.',
      },
    },
  },
  'bruns-lutkepohl-2023': {
    id: 'bruns-lutkepohl-2023',
    citationKey: 'bruns2022AlternativeBootstrapProxyVector',
    bibtexPath: 'vault/citations/bibtex/bruns-2022-alternative-bootstrap-proxy-vector-autoregressions-f787d518.bib',
    type: 'article',
    authors: ['Martin Bruns', 'Helmut Lütkepohl'],
    year: 2023,
    title: 'An Alternative Bootstrap for Proxy Vector Autoregressions',
    venue: 'Computational Economics',
    volume: '62',
    issue: '4',
    pages: '1857–1882',
    doi: '10.1007/s10614-022-10323-w',
    url: 'https://doi.org/10.1007/s10614-022-10323-w',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    versionNote: 'Published online in 2022; version of record issued in volume 62 (2023).',
    pageUses: {
      proxy: {
        order: 10,
        listed: true,
        annotation: 'a structured proxy-residual bootstrap designed to improve small-sample coverage in suitable proxy data-generating processes.',
      },
    },
  },
  'angelini-cavaliere-fanelli-2024': {
    id: 'angelini-cavaliere-fanelli-2024',
    citationKey: 'angelini2024IdentificationTestingStrategyProxy',
    bibtexPath: 'vault/citations/bibtex/angelini-2024-identification-testing-strategy-proxy-svars-weak-proxies-b74a9baf.bib',
    vaultDiscrepancy: 'Vault DOI/article number are stale; Atlas metadata was rechecked against the Journal of Econometrics version of record.',
    type: 'article',
    authors: ['Giovanni Angelini', 'Giuseppe Cavaliere', 'Luca Fanelli'],
    year: 2024,
    title: 'An Identification and Testing Strategy for Proxy-SVARs with Weak Proxies',
    venue: 'Journal of Econometrics',
    volume: '238',
    issue: '2',
    articleNumber: '105604',
    doi: '10.1016/j.jeconom.2023.105604',
    url: 'https://doi.org/10.1016/j.jeconom.2023.105604',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 11,
        listed: true,
        annotation: 'an indirect identification route using strong non-target proxies plus a bootstrap relevance diagnostic.',
      },
    },
  },
  'arias-rubio-ramirez-waggoner-2021': {
    id: 'arias-rubio-ramirez-waggoner-2021',
    citationKey: 'arias2021InferenceBayesianProxySvars',
    bibtexPath: 'vault/citations/bibtex/arias-2021-inference-bayesian-proxy-svars-c3418c6a.bib',
    vaultDiscrepancy: 'Vault DOI is stale; Atlas metadata was rechecked against the Journal of Econometrics version of record.',
    type: 'article',
    authors: ['Jonas E. Arias', 'Juan F. Rubio-Ramírez', 'Daniel F. Waggoner'],
    year: 2021,
    title: 'Inference in Bayesian Proxy-SVARs',
    venue: 'Journal of Econometrics',
    volume: '225',
    issue: '1',
    pages: '88–106',
    doi: '10.1016/j.jeconom.2020.12.004',
    url: 'https://doi.org/10.1016/j.jeconom.2020.12.004',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 12,
        listed: true,
        annotation: 'exact Bayesian posterior simulation with proxy exogeneity/relevance and additional sign or zero restrictions.',
      },
    },
  },
  'giacomini-kitagawa-read-2022': {
    id: 'giacomini-kitagawa-read-2022',
    citationKey: 'giacomini2022RobustBayesianInferenceProxy',
    bibtexPath: 'vault/citations/bibtex/giacomini-2022-robust-bayesian-inference-proxy-svars-420bd240.bib',
    vaultDiscrepancy: 'Vault DOI is stale; Atlas metadata was rechecked against the Journal of Econometrics version of record.',
    type: 'article',
    authors: ['Raffaella Giacomini', 'Toru Kitagawa', 'Matthew Read'],
    year: 2022,
    title: 'Robust Bayesian Inference in Proxy SVARs',
    venue: 'Journal of Econometrics',
    volume: '228',
    issue: '1',
    pages: '107–126',
    doi: '10.1016/j.jeconom.2021.02.003',
    url: 'https://doi.org/10.1016/j.jeconom.2021.02.003',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 13,
        listed: true,
        annotation: 'robust multiple-prior Bayesian inference when proxy restrictions leave impulse responses or FEVDs set identified.',
      },
    },
  },
  'braun-brueggemann-2023': {
    id: 'braun-brueggemann-2023',
    citationKey: 'braun2022IdentificationSvarModelsCombining',
    bibtexPath: 'vault/citations/bibtex/braun-2022-identification-svar-models-combining-sign-restrictions-external-instruments-bf506e1c.bib',
    type: 'article',
    authors: ['Robin Braun', 'Ralf Brüggemann'],
    year: 2023,
    title: 'Identification of SVAR Models by Combining Sign Restrictions with External Instruments',
    venue: 'Journal of Business & Economic Statistics',
    volume: '41',
    issue: '4',
    pages: '1077–1089',
    doi: '10.1080/07350015.2022.2104857',
    url: 'https://doi.org/10.1080/07350015.2022.2104857',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    versionNote: 'Published online in 2022; version of record is in volume 41 (2023).',
    pageUses: {
      sign: {
        order: 9,
        listed: true,
        annotation: 'a hybrid design combining sign restrictions with valid or plausibly exogenous external instruments.',
      },
      proxy: {
        order: 14,
        listed: true,
        annotation: 'combines valid or plausibly exogenous proxies with sign restrictions and Bayesian overidentification checks.',
      },
    },
  },
  'bruns-lutkepohl-mcneil-2025': {
    id: 'bruns-lutkepohl-mcneil-2025',
    citationKey: 'bruns2025AvoidingUnintentionallyCorrelatedShocks',
    bibtexPath: 'vault/citations/bibtex/bruns-2025-avoiding-unintentionally-correlated-shocks-proxy-vector-autoregressive-analysis-a4908307.bib',
    type: 'article',
    authors: ['Martin Bruns', 'Helmut Lütkepohl', 'James McNeil'],
    year: 2025,
    title: 'Avoiding Unintentionally Correlated Shocks in Proxy Vector Autoregressive Analysis',
    venue: 'Journal of Business & Economic Statistics',
    volume: '43',
    issue: '4',
    pages: '1119–1131',
    doi: '10.1080/07350015.2025.2476699',
    url: 'https://doi.org/10.1080/07350015.2025.2476699',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 15,
        listed: true,
        annotation: 'shows why one-by-one multi-proxy estimates can produce correlated shocks and supplies a joint GMM diagnostic and estimator.',
      },
    },
  },
  'kanzig-2021-oil-supply-news': {
    id: 'kanzig-2021-oil-supply-news',
    citationKey: 'kanzig2021MacroeconomicEffectsOilSupply',
    bibtexPath: 'vault/citations/bibtex/kanzig-2021-macroeconomic-effects-oil-supply-news-evidence-opec-announcements-a18f9b4a.bib',
    type: 'article',
    authors: ['Diego R. Känzig'],
    year: 2021,
    title: 'The Macroeconomic Effects of Oil Supply News: Evidence from OPEC Announcements',
    venue: 'American Economic Review',
    volume: '111',
    issue: '4',
    pages: '1092–1125',
    doi: '10.1257/aer.20190964',
    url: 'https://doi.org/10.1257/aer.20190964',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    pageUses: {
      proxy: {
        order: 16,
        listed: true,
        annotation: 'a representative commodity application built from high-frequency OPEC announcement surprises.',
      },
    },
  },
  'kanzig-2023-carbon-pricing-r2025': {
    id: 'kanzig-2023-carbon-pricing-r2025',
    citationKey: 'kanzig2025UnequalEconomicConsequencesCarbonPricing',
    bibtexPath: 'vault/citations/bibtex/kanzig-2025-unequal-economic-consequences-carbon-pricing-cd887ea9.bib',
    type: 'working-paper',
    authors: ['Diego R. Känzig'],
    year: 2023,
    displayYear: '2023, rev. 2025',
    title: 'The Unequal Economic Consequences of Carbon Pricing',
    venue: 'NBER Working Paper 31221',
    doi: '10.3386/w31221',
    url: 'https://doi.org/10.3386/w31221',
    metadataStatus: 'verified-primary',
    verifiedAt: '2026-07-15',
    versionNote: 'NBER issue date May 2023; registry checked against the September 2025 revision record.',
    pageUses: {
      proxy: {
        order: 17,
        listed: true,
        annotation: 'a public working-paper application using EU ETS regulatory-event surprises as an instrument for carbon-policy shocks.',
      },
    },
  },
  ...methodSources,
};

export default atlasSources;
